"""
generate_foundations_rag_notebooks.py
=============================================================================
Programmatic generator for the 3 Foundations & RAG companion Jupyter notebooks:
1. notebooks/00_token_mechanics_and_kv_cache.ipynb (Phase 00 companion)
2. notebooks/01_prompt_caching_and_budgeting.ipynb (Phase 01 companion)
3. notebooks/02_hybrid_rag_and_rrf_visualizer.ipynb (Lab 01 & Phase 02 companion)

Strictly adheres to:
- 100% valid JSON and Colab bootstrap setup
- Pure Markdown & Zero-LaTeX (no $$, $, \frac, etc.; clean text code blocks and Unicode)
- No meta-directive leaks
=============================================================================
"""

import json
import sys
from pathlib import Path

# Add project root and scripts to sys.path
repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root))
from scripts.nb_helper import NotebookBuilder


def build_notebook_00(output_path: Path):
    """Builds Notebook 00: Token Mechanics, KV-Cache Physics & Roofline Hardware Ceilings."""
    nb = NotebookBuilder(
        title="00: Token Mechanics, KV-Cache Physics & Roofline Hardware Ceilings",
        description=(
            "> **Curriculum Phase**: `Phase 00 - Foundations & Token Mechanics`  \n"
            "> **Prerequisites**: Python 3.12+, basic understanding of transformer inference  \n"
            "> **Key Concepts**: Byte-Pair Encoding (BPE), Subword Tokenization Ratios, KV-Cache Memory Bandwidth, Attention Architectures (MHA, GQA, MLA), and the Hardware Roofline Model.  \n\n"
            "Welcome to the interactive companion notebook for **Phase 00: Foundations and Token Mechanics**. "
            "In this hands-on lab, you will move beyond high-level prompt abstractions and explore the physical mechanics of Large Language Models:\n\n"
            "1. **Tokenization Mechanics**: How Byte-Pair Encoding (BPE) turns UTF-8 bytes into subword tokens, and why multi-lingual texts or formatted numbers suffer from the tokenization tax.\n"
            "2. **KV-Cache VRAM & Bandwidth Sizing**: Deriving exact GPU memory allocations across Multi-Head Attention (MHA), Grouped-Query Attention (GQA), and Multi-Head Latent Attention (MLA) across 4K, 32K, and 128K context windows.\n"
            "3. **The Inference Roofline Model**: Plotting memory-bandwidth vs compute ceilings to understand why prefill is compute-bound while autoregressive token generation (decode) is memory-bandwidth bound."
        )
    )

    # Cell 1: Environment & Imports
    nb.add_markdown(
        "### Environment Setup & Dependencies\n\n"
        "We import standard analytical and visualization libraries. If running in Google Colab, the bootstrap cell above has cloned the repository and installed all requirements."
    )
    nb.add_code(
        "import math\n"
        "import re\n"
        "from typing import Dict, List, Tuple\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from pydantic import BaseModel, Field\n\n"
        "# Configure clean visualization aesthetics\n"
        "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n"
        "plt.rcParams['font.sans-serif'] = 'DejaVu Sans'\n"
        "plt.rcParams['figure.dpi'] = 120\n\n"
        "print('Dependencies loaded successfully.')"
    )

    # Cell 2: Part 1 Markdown
    nb.add_markdown(
        "## Part 1: Tokenization Mechanics: Byte-Pair Encoding (BPE) from Scratch\n\n"
        "A transformer model never processes raw characters or strings. It receives an array of integers representing discrete vocabulary entries. "
        "Modern tokenizers use **Byte-Pair Encoding (BPE)** (Sennrich et al., 2015), which builds a subword vocabulary by iteratively counting adjacent symbol pairs and merging the most frequent pair into a new symbol.\n\n"
        "### How BPE Training Works:\n"
        "1. **Initialization**: Start with a base vocabulary of single symbols (e.g. all 256 byte values or base characters).\n"
        "2. **Frequency Counting**: Count every adjacent pair of symbols across the training corpus.\n"
        "3. **Merge Step**: Find the most frequent pair, replace all occurrences in the corpus with a newly created merged token, and append this rule to the merge table.\n"
        "4. **Iterate**: Repeat until the target vocabulary size or merge count is reached.\n\n"
        "At inference time, the tokenizer applies these learned merges in exact historical order to segment any arbitrary string into subwords."
    )

    # Cell 3: Part 1 Code - ToyBPETokenizer
    nb.add_code(
        "class ToyBPETokenizer:\n"
        "    \"\"\"An educational Byte-Pair Encoding (BPE) tokenizer demonstrating subword splitting.\"\"\"\n\n"
        "    def __init__(self, target_merges: int = 15):\n"
        "        self.target_merges = target_merges\n"
        "        self.merges: List[Tuple[str, str, str]] = []  # (pair_0, pair_1, merged_token)\n"
        "        self.vocab: Dict[int, str] = {}\n"
        "        self.token_to_id: Dict[str, int] = {}\n\n"
        "    def get_stats(self, word_freqs: Dict[Tuple[str, ...], int]) -> Dict[Tuple[str, str], int]:\n"
        "        pairs: Dict[Tuple[str, str], int] = {}\n"
        "        for word_tuple, freq in word_freqs.items():\n"
        "            for i in range(len(word_tuple) - 1):\n"
        "                pair = (word_tuple[i], word_tuple[i + 1])\n"
        "                pairs[pair] = pairs.get(pair, 0) + freq\n"
        "        return pairs\n\n"
        "    def merge_word(self, word_tuple: Tuple[str, ...], pair: Tuple[str, str], new_token: str) -> Tuple[str, ...]:\n"
        "        new_word = []\n"
        "        i = 0\n"
        "        while i < len(word_tuple):\n"
        "            if i < len(word_tuple) - 1 and word_tuple[i] == pair[0] and word_tuple[i + 1] == pair[1]:\n"
        "                new_word.append(new_token)\n"
        "                i += 2\n"
        "            else:\n"
        "                new_word.append(word_tuple[i])\n"
        "                i += 1\n"
        "        return tuple(new_word)\n\n"
        "    def train(self, corpus: str):\n"
        "        # Split words into characters with end-of-word marker </w>\n"
        "        words = corpus.strip().split()\n"
        "        word_freqs: Dict[Tuple[str, ...], int] = {}\n"
        "        for w in words:\n"
        "            symbols = tuple(list(w) + [\"</w>\"])\n"
        "            word_freqs[symbols] = word_freqs.get(symbols, 0) + 1\n\n"
        "        # Initialize vocabulary with unique characters\n"
        "        base_vocab = set()\n"
        "        for symbols in word_freqs.keys():\n"
        "            base_vocab.update(symbols)\n\n"
        "        current_id = 0\n"
        "        for sym in sorted(base_vocab):\n"
        "            self.vocab[current_id] = sym\n"
        "            self.token_to_id[sym] = current_id\n"
        "            current_id += 1\n\n"
        "        print(f\"Initial base character vocabulary size: {len(self.vocab)}\")\n\n"
        "        # Iteratively find and merge most frequent pairs\n"
        "        for step in range(self.target_merges):\n"
        "            pairs = self.get_stats(word_freqs)\n"
        "            if not pairs:\n"
        "                break\n"
        "            best_pair = max(pairs, key=pairs.get)\n"
        "            count = pairs[best_pair]\n"
        "            new_token = best_pair[0] + best_pair[1]\n"
        "            self.merges.append((best_pair[0], best_pair[1], new_token))\n"
        "            self.vocab[current_id] = new_token\n"
        "            self.token_to_id[new_token] = current_id\n"
        "            current_id += 1\n\n"
        "            # Update corpus word representations\n"
        "            new_word_freqs = {}\n"
        "            for w_tuple, freq in word_freqs.items():\n"
        "                merged = self.merge_word(w_tuple, best_pair, new_token)\n"
        "                new_word_freqs[merged] = freq\n"
        "            word_freqs = new_word_freqs\n\n"
        "        print(f\"Completed {len(self.merges)} merges. Total vocabulary size: {len(self.vocab)}\")\n\n"
        "    def encode(self, text: str) -> List[str]:\n"
        "        tokens = []\n"
        "        for w in text.strip().split():\n"
        "            w_tuple = tuple(list(w) + [\"</w>\"])\n"
        "            for p0, p1, merged in self.merges:\n"
        "                w_tuple = self.merge_word(w_tuple, (p0, p1), merged)\n"
        "            tokens.extend(list(w_tuple))\n"
        "        return tokens\n\n"
        "# Train Toy BPE on representative domain corpus\n"
        "corpus = (\n"
        "    \"low lower lowest newest widest \"\n"
        "    \"unbreakable break breaks breaking unbreak \"\n"
        "    \"lower lower lowest lowest newest \"\n"
        "    \"widest break breaking unbreakable\"\n"
        ")\n"
        "tokenizer = ToyBPETokenizer(target_merges=12)\n"
        "tokenizer.train(corpus)\n\n"
        "# Inspect learned merge operations\n"
        "merge_df = pd.DataFrame(tokenizer.merges, columns=[\"Pair 0\", \"Pair 1\", \"Merged Subword Token\"])\n"
        "merge_df.index = [f\"Merge {i+1}\" for i in range(len(merge_df))]\n"
        "display(merge_df)\n\n"
        "# Test subword splitting on unseen words\n"
        "test_words = [\"lowest\", \"unbreakable\", \"newer\", \"wider\", \"breaker\"]\n"
        "print(\"\\n--- Subword Splitting Inference ---\")\n"
        "for tw in test_words:\n"
        "    pieces = tokenizer.encode(tw)\n"
        "    print(f\"Input: '{tw:<12}' -> Subwords: {pieces}\")"
    )

    # Cell 4: Multilingual & Format Analysis Markdown
    nb.add_markdown(
        "### Character vs Byte vs Token Ratio Comparison\n\n"
        "Because BPE vocabularies are trained predominantly on English-dominated web crawls, common English words are assigned single token IDs. "
        "In contrast, non-English languages, structured code, and formatted numbers are split into multiple fine-grained subwords or raw UTF-8 byte tokens.\n\n"
        "This introduces critical production implications:\n"
        "- **The Non-English Token Tax**: The exact same semantic statement costs 2x to 5x more tokens in Hindi, Japanese, or German than in English.\n"
        "- **Formatted Numbers**: `1,000,000` often splits into 3–5 tokens (`1`, `,`, `000`, `,`, `000`), whereas `1000000` is 2 tokens.\n"
        "- **Whitespace Sensitivity**: In modern tokenizers (like OpenAI `cl100k_base` and `o200k_base`), leading spaces are glued to words. `\" Hello\"` is 1 token, while `\"  Hello\"` (double space) becomes 2 tokens."
    )

    # Cell 5: Multilingual Code & Tokenizer Benchmark
    nb.add_code(
        "try:\n"
        "    import tiktoken\n"
        "    enc = tiktoken.get_encoding(\"cl100k_base\")\n"
        "    tokenize_fn = lambda txt: enc.encode(txt)\n"
        "    tokenizer_name = \"tiktoken cl100k_base\"\n"
        "except Exception:\n"
        "    # Deterministic fallback estimator matching empirical BPE splitting patterns\n"
        "    def tokenize_fn(txt: str) -> List[int]:\n"
        "        # Approximate subwords by splitting alphanumeric words and non-ASCII clusters\n"
        "        subwords = re.findall(r\"[\\w']+|[\\s]+|[^\\w\\s]\", txt, re.UNICODE)\n"
        "        expanded = []\n"
        "        for sw in subwords:\n"
        "            if any(ord(c) > 127 for c in sw):\n"
        "                # Non-ASCII UTF-8 multibyte expansion (~1.5 to 2 tokens per 3 bytes)\n"
        "                expanded.extend([1] * max(1, math.ceil(len(sw.encode('utf-8')) / 2)))\n"
        "            elif len(sw) > 4:\n"
        "                expanded.extend([1] * math.ceil(len(sw) / 4))\n"
        "            else:\n"
        "                expanded.append(1)\n"
        "        return expanded\n"
        "    tokenizer_name = \"heuristic subword model\"\n\n"
        "sample_texts = {\n"
        "    \"English\": \"The refund policy allows returns within thirty days.\",\n"
        "    \"Spanish\": \"La política de reembolso permite devoluciones en un plazo de treinta días.\",\n"
        "    \"German\": \"Die Rückerstattungsrichtlinie ermöglicht Rückgaben innerhalb von dreißig Tagen.\",\n"
        "    \"Hindi\": \"धनवापसी नीति तीस दिनों के भीतर वापसी की अनुमति देती है।\",\n"
        "    \"Japanese\": \"返金ポリシーにより、30日以内の返品が可能です。\",\n"
        "    \"Chinese\": \"退款政策允许在三十天内退货。\",\n"
        "    \"Code (camelCase)\": \"def getUserById(userId: str) -> dict: return {'id': userId}\",\n"
        "    \"Code (snake_case)\": \"def get_user_by_id(user_id: str) -> dict: return {'id': user_id}\",\n"
        "    \"Formatted Number\": \"Total revenue was $1,000,000 in Q4.\",\n"
        "    \"Raw Number\": \"Total revenue was $1000000 in Q4.\",\n"
        "}\n\n"
        "data_rows = []\n"
        "english_tokens = len(tokenize_fn(sample_texts[\"English\"]))\n\n"
        "for label, text in sample_texts.items():\n"
        "    tokens = tokenize_fn(text)\n"
        "    n_tokens = len(tokens)\n"
        "    n_chars = len(text)\n"
        "    n_bytes = len(text.encode('utf-8'))\n"
        "    expansion = n_tokens / english_tokens if \"English\" in sample_texts else 1.0\n"
        "    data_rows.append({\n"
        "        \"Category / Language\": label,\n"
        "        \"Characters\": n_chars,\n"
        "        \"UTF-8 Bytes\": n_bytes,\n"
        "        \"Tokens\": n_tokens,\n"
        "        \"Chars / Token\": round(n_chars / n_tokens, 2),\n"
        "        \"Bytes / Token\": round(n_bytes / n_tokens, 2),\n"
        "        \"Relative Cost (vs English)\": f\"{expansion:.2f}x\"\n"
        "    })\n\n"
        "bench_df = pd.DataFrame(data_rows)\n"
        "print(f\"Tokenizer Active: {tokenizer_name}\")\n"
        "display(bench_df)"
    )

    # Cell 6: Matplotlib Tokenization Chart
    nb.add_code(
        "# Visualizing the Multilingual Token Tax\n"
        "languages = [\"English\", \"Spanish\", \"German\", \"Hindi\", \"Japanese\", \"Chinese\"]\n"
        "lang_df = bench_df[bench_df[\"Category / Language\"].isin(languages)].copy()\n"
        "lang_df[\"Multiplier\"] = [float(x.replace('x', '')) for x in lang_df[\"Relative Cost (vs English)\"]]\n\n"
        "fig, ax = plt.subplots(figsize=(9, 4.5))\n"
        "bars = ax.barh(lang_df[\"Category / Language\"], lang_df[\"Tokens\"], color=[\"#2563eb\", \"#0284c7\", \"#0d9488\", \"#dc2626\", \"#d97706\", \"#7c3aed\"])\n"
        "ax.set_xlabel(\"Token Count for Identical Semantic Refund Policy\")\n"
        "ax.set_title(\"The Tokenization Tax: Semantic Equivalence vs Token Cost Across Languages\", fontsize=12, pad=12)\n"
        "ax.grid(axis='x', linestyle='--', alpha=0.7)\n\n"
        "for bar, mult in zip(bars, lang_df[\"Multiplier\"]):\n"
        "    width = bar.get_width()\n"
        "    ax.text(width + 0.5, bar.get_y() + bar.get_height() / 2, f\"{int(width)} tokens ({mult:.1f}x)\",\n"
        "            va='center', fontsize=9, fontweight='bold')\n\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 7: Part 2 Markdown
    nb.add_markdown(
        "## Part 2: KV-Cache Memory Bandwidth and VRAM Sizing Calculator\n\n"
        "During autoregressive token generation, recomputing Key and Value tensors for all preceding tokens at every step would yield quadratic O(N²) compute latency. "
        "The **Key-Value (KV) Cache** stores previous Key and Value projection tensors in GPU High-Bandwidth Memory (HBM).\n\n"
        "### The KV-Cache Memory Formula\n"
        "For a model with `n_layers`, `n_kv_heads`, head dimension `d_head`, precision `bytes_per_elem` (2 for FP16/BF16, 1 for FP8), context length `seq_len`, and batch size `B`:\n\n"
        "```text\n"
        "KV_Cache_Bytes = 2 × n_layers × n_kv_heads × d_head × bytes_per_elem × seq_len × batch_size\n"
        "```\n\n"
        "The factor of 2 accounts for both the **Key** and **Value** tensors.\n\n"
        "### Architectural Levers: MHA vs GQA vs MLA\n"
        "- **Multi-Head Attention (MHA)** (e.g. Llama 2 70B): `n_kv_heads = n_heads = 64`. Maximum VRAM footprint.\n"
        "- **Grouped-Query Attention (GQA)** (e.g. Llama 3.1 70B): `n_kv_heads = 8`, while query heads = 64. Groups share KV heads, yielding an **8x KV cache reduction**.\n"
        "- **Multi-Head Latent Attention (MLA)** (e.g. DeepSeek-V2 / V3): Instead of storing full uncompressed keys/values, caches a compressed low-rank latent vector per token (`d_c + d_h_R` = 512 + 64 = 576 dimensions). This delivers a **93.3% KV cache reduction**."
    )

    # Cell 8: Part 2 Code - Calculator
    nb.add_code(
        "class ModelConfig(BaseModel):\n"
        "    name: str\n"
        "    layers: int = Field(gt=0)\n"
        "    query_heads: int = Field(gt=0)\n"
        "    kv_heads: int = Field(gt=0)\n"
        "    head_dim: int = Field(gt=0)\n"
        "    param_count_billions: float = Field(gt=0)\n"
        "    attention_type: str\n"
        "    mla_latent_dim: int = 0  # Only for MLA\n\n"
        "    def kv_bytes_per_token(self, bytes_per_elem: int = 2) -> int:\n"
        "        if self.attention_type == \"MLA\":\n"
        "            # MLA caches compressed latent representation: (d_c + d_h_R) per layer\n"
        "            return self.layers * self.mla_latent_dim * bytes_per_elem\n"
        "        # Standard MHA / GQA formula: 2 (Key + Value) * layers * kv_heads * head_dim * bytes\n"
        "        return 2 * self.layers * self.kv_heads * self.head_dim * bytes_per_elem\n\n"
        "    def weights_vram_gb(self, bytes_per_elem: int = 2) -> float:\n"
        "        return (self.param_count_billions * 1e9 * bytes_per_elem) / (1024 ** 3)\n\n"
        "    def kv_cache_vram_gb(self, seq_len: int, batch_size: int = 1, bytes_per_elem: int = 2) -> float:\n"
        "        total_bytes = self.kv_bytes_per_token(bytes_per_elem) * seq_len * batch_size\n"
        "        return total_bytes / (1024 ** 3)\n\n"
        "# Define concrete enterprise model architectures\n"
        "models = [\n"
        "    ModelConfig(\n"
        "        name=\"Llama-2-70B (MHA)\",\n"
        "        layers=80, query_heads=64, kv_heads=64, head_dim=128,\n"
        "        param_count_billions=70.0, attention_type=\"MHA\"\n"
        "    ),\n"
        "    ModelConfig(\n"
        "        name=\"Llama-3.1-70B (GQA)\",\n"
        "        layers=80, query_heads=64, kv_heads=8, head_dim=128,\n"
        "        param_count_billions=70.0, attention_type=\"GQA\"\n"
        "    ),\n"
        "    ModelConfig(\n"
        "        name=\"DeepSeek-V3-671B (MLA)\",\n"
        "        layers=61, query_heads=128, kv_heads=128, head_dim=128,\n"
        "        param_count_billions=671.0, attention_type=\"MLA\", mla_latent_dim=576\n"
        "    ),\n"
        "]\n\n"
        "context_windows = [4_096, 32_768, 131_072]  # 4K, 32K, 128K\n"
        "concurrency_levels = [1, 16, 64]\n\n"
        "rows = []\n"
        "for m in models:\n"
        "    bytes_per_tok = m.kv_bytes_per_token(bytes_per_elem=2)\n"
        "    for ctx in context_windows:\n"
        "        for b in concurrency_levels:\n"
        "            kv_gb = m.kv_cache_vram_gb(seq_len=ctx, batch_size=b, bytes_per_elem=2)\n"
        "            rows.append({\n"
        "                \"Model\": m.name,\n"
        "                \"Attention\": m.attention_type,\n"
        "                \"Bytes/Token (FP16)\": f\"{bytes_per_tok:,} B\",\n"
        "                \"Context Window\": f\"{ctx // 1024}K ({ctx:,})\",\n"
        "                \"Batch Size\": b,\n"
        "                \"KV Cache VRAM (GB)\": round(kv_gb, 2),\n"
        "            })\n\n"
        "kv_df = pd.DataFrame(rows)\n"
        "# Filter for key representative snapshot to display\n"
        "snapshot_df = kv_df[(kv_df[\"Batch Size\"] == 16) | ((kv_df[\"Context Window\"] == \"128K (131,072)\") & (kv_df[\"Batch Size\"] == 1))]\n"
        "display(snapshot_df.reset_index(drop=True))"
    )

    # Cell 9: Memory Bandwidth & Decode TPS Ceiling
    nb.add_markdown(
        "### Hardware Physics: Memory Bandwidth & Decode TPS Ceiling\n\n"
        "Why is LLM generation memory-bandwidth bound? During autoregressive decoding, every single token generation step requires the GPU to:\n"
        "1. Stream all model weights from HBM into on-chip SRAM to execute linear matrix projections.\n"
        "2. Stream the accumulated KV cache for the active batch to compute attention.\n\n"
        "```text\n"
        "Memory Moved Per Step (Bytes) = Model_Weight_Bytes + KV_Cache_Bytes_for_Active_Batch\n"
        "Theoretical Decode TPS Ceiling = Memory_Bandwidth_Bytes_sec ÷ Memory_Moved_Per_Step\n"
        "```\n\n"
        "On an **NVIDIA H100 SXM (80 GB HBM3, 3,350 GB/s bandwidth)**, we can compute the absolute ceiling of tokens per second across batch sizes and context lengths:"
    )

    # Cell 10: Decode TPS Code
    nb.add_code(
        "h100_bandwidth_gbs = 3350.0  # 3.35 TB/s in decimal GB/s\n"
        "h100_vram_gb = 80.0\n\n"
        "tps_results = []\n"
        "llama3 = models[1]  # Llama-3.1-70B\n"
        "model_weight_gb = llama3.weights_vram_gb(bytes_per_elem=2)  # FP16 ~ 130.4 GB (requires 2x H100 or tensor parallel TP=2)\n"
        "# Assuming TP=2 setup (2x H100 SXM, aggregated bandwidth = 6,700 GB/s, 160 GB VRAM)\n"
        "tp2_bandwidth_gbs = h100_bandwidth_gbs * 2\n\n"
        "for ctx in [2_048, 8_192, 32_768, 65_536]:\n"
        "    for b in [1, 8, 32, 64]:\n"
        "        kv_gb = llama3.kv_cache_vram_gb(seq_len=ctx, batch_size=b, bytes_per_elem=2)\n"
        "        total_bytes_moved_gb = model_weight_gb + kv_gb\n"
        "        max_system_tps = (tp2_bandwidth_gbs / total_bytes_moved_gb) * b\n"
        "        tps_per_user = max_system_tps / b\n"
        "        tps_results.append({\n"
        "            \"Context Length\": f\"{ctx // 1024}K\",\n"
        "            \"Batch Size\": b,\n"
        "            \"Weight VRAM (GB)\": round(model_weight_gb, 1),\n"
        "            \"KV Cache VRAM (GB)\": round(kv_gb, 2),\n"
        "            \"Total VRAM Moved/Step (GB)\": round(total_bytes_moved_gb, 2),\n"
        "            \"Aggregate System TPS\": round(max_system_tps, 1),\n"
        "            \"Per-User TPS\": round(tps_per_user, 1)\n"
        "        })\n\n"
        "tps_df = pd.DataFrame(tps_results)\n"
        "display(tps_df[tps_df[\"Batch Size\"].isin([1, 32])].reset_index(drop=True))"
    )

    # Cell 11: Matplotlib KV-Cache Sizing Comparison Chart
    nb.add_code(
        "# Visualizing KV Cache Footprint at 128K context across attention mechanisms\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n\n"
        "batch_sizes = [1, 8, 32, 64]\n"
        "x = np.arange(len(batch_sizes))\n"
        "width = 0.25\n\n"
        "colors = [\"#dc2626\", \"#2563eb\", \"#16a34a\"]\n"
        "for idx, m in enumerate(models):\n"
        "    vrams = [m.kv_cache_vram_gb(seq_len=131_072, batch_size=b, bytes_per_elem=2) for b in batch_sizes]\n"
        "    offset = (idx - 1) * width\n"
        "    bars = ax.bar(x + offset, vrams, width, label=m.name, color=colors[idx])\n"
        "    for bar in bars:\n"
        "        height = bar.get_height()\n"
        "        if height > 0.1:\n"
        "            ax.text(bar.get_x() + bar.get_width() / 2, height + 2,\n"
        "                    f\"{height:.0f}G\", ha='center', va='bottom', fontsize=8)\n\n"
        "ax.axhline(80, color='black', linestyle='--', linewidth=1.5, label='1x H100 80GB VRAM Limit')\n"
        "ax.axhline(160, color='purple', linestyle=':', linewidth=1.5, label='2x H100 160GB VRAM Limit')\n"
        "ax.set_xlabel('Concurrency Batch Size (Simultaneous Streams)')\n"
        "ax.set_ylabel('KV-Cache VRAM Required (GB) at 128K Context')\n"
        "ax.set_title('KV-Cache VRAM Demand at 128K Context: MHA vs GQA vs MLA', fontsize=12, pad=12)\n"
        "ax.set_xticks(x)\n"
        "ax.set_xticklabels([f'Batch {b}' for b in batch_sizes])\n"
        "ax.legend(loc='upper left')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 12: Part 3 Markdown
    nb.add_markdown(
        "## Part 3: The Inference Roofline Model: Arithmetic Intensity vs Hardware Ceilings\n\n"
        "The **Roofline Model** (Williams, Waterman & Patterson, 2008) provides a visual blueprint of system performance by plotting **Attainable FLOP/s** against **Arithmetic Intensity** (FLOPs per byte of memory transferred).\n\n"
        "### Mathematical Formulation:\n"
        "```text\n"
        "Attainable FLOP/s = min( Peak FLOP/s , Memory_Bandwidth × Arithmetic_Intensity )\n"
        "Ridge Point (Balance Point) = Peak FLOP/s ÷ Memory_Bandwidth\n"
        "```\n\n"
        "- **To the left of the Ridge Point (Slanted Ceiling)**: The workload is **memory-bandwidth bound**. Compute units are idle waiting for tensors to stream from HBM. Increasing compute capacity yields zero speedup.\n"
        "- **To the right of the Ridge Point (Flat Ceiling)**: The workload is **compute-bound**. Memory channels are saturated with reuse. Peak Tensor Core throughput is the governing limit.\n\n"
        "### LLM Serving Phases on the Roofline:\n"
        "1. **Prefill Phase (Prompt Ingestion)**: Processes all prompt tokens in parallel. Weights are reused across all prompt tokens `T`. Arithmetic intensity scales roughly as `T` FLOPs/byte (e.g. 512 to 4,096 FLOPs/byte), placing prefill firmly in the **compute-bound** regime.\n"
        "2. **Decode Phase (Token Generation, Batch=1)**: Reads the entire model weights tensor just to emit a single token. Arithmetic intensity is ~1.0 to 1.5 FLOPs/byte, trapping it deep in the **memory-bandwidth bound** regime.\n"
        "3. **Batched Decode (Batch=64)**: Shares weight reads across 64 concurrently generated tokens, elevating arithmetic intensity to ~64 FLOPs/byte and climbing toward the ridge point."
    )

    # Cell 13: Roofline Code & Matplotlib Plot
    nb.add_code(
        "# NVIDIA H100 SXM5 Hardware Parameters (Dense FP16/BF16 Tensor Core)\n"
        "peak_tflops = 1979.0         # 1,979 TFLOPS\n"
        "bandwidth_tb_s = 3.35        # 3.35 TB/s = 3,350 GB/s\n"
        "bandwidth_gb_s = bandwidth_tb_s * 1000.0\n"
        "ridge_point = (peak_tflops * 1e12) / (bandwidth_gb_s * 1e9)  # FLOPs per byte\n\n"
        "intensities = np.logspace(-0.5, 4.0, 500)  # From ~0.3 to 10,000 FLOPs/byte\n"
        "attainable_tflops = np.minimum(peak_tflops, (bandwidth_gb_s * intensities) / 1e3)\n\n"
        "fig, ax = plt.subplots(figsize=(10, 6))\n"
        "ax.loglog(intensities, attainable_tflops, 'b-', linewidth=2.5, label='NVIDIA H100 SXM Roofline')\n\n"
        "# Mark the Ridge Point\n"
        "ax.plot(ridge_point, peak_tflops, 'ro', markersize=8, label=f'Ridge Point ({ridge_point:.1f} FLOPs/byte)')\n"
        "ax.axvline(ridge_point, color='gray', linestyle=':', alpha=0.6)\n\n"
        "# Operational Workload Points\n"
        "workloads = [\n"
        "    (\"Decode (Batch 1)\", 1.2, (bandwidth_gb_s * 1.2) / 1e3, \"#dc2626\"),\n"
        "    (\"Decode (Batch 16)\", 18.0, (bandwidth_gb_s * 18.0) / 1e3, \"#d97706\"),\n"
        "    (\"Decode (Batch 64)\", 72.0, (bandwidth_gb_s * 72.0) / 1e3, \"#ca8a04\"),\n"
        "    (\"Prefill (Seq 512)\", 512.0, min(peak_tflops, (bandwidth_gb_s * 512.0) / 1e3), \"#059669\"),\n"
        "    (\"Prefill (Seq 4096)\", 2048.0, peak_tflops, \"#2563eb\"),\n"
        "]\n\n"
        "for label, intensity, tflops, color in workloads:\n"
        "    ax.plot(intensity, tflops, marker='s', markersize=9, color=color, label=f\"{label} ({intensity:.1f} F/B)\")\n"
        "    ax.annotate(f\"  {label}\", (intensity, tflops), fontsize=9, fontweight='bold', color=color,\n"
        "                verticalalignment='center')\n\n"
        "# Shaded Architectural Regimes\n"
        "ax.axvspan(0.3, ridge_point, color='red', alpha=0.06, label='Memory-Bandwidth Bound Zone')\n"
        "ax.axvspan(ridge_point, 10000, color='green', alpha=0.06, label='Compute-Bound Zone')\n\n"
        "ax.set_xlabel('Arithmetic Intensity (FLOPs / Byte transferred)', fontsize=11)\n"
        "ax.set_ylabel('Attainable Throughput (TFLOPS)', fontsize=11)\n"
        "ax.set_title('The Inference Roofline Model: Prefill vs Autoregressive Decode Regimes', fontsize=13, pad=12)\n"
        "ax.set_xlim(0.3, 10000)\n"
        "ax.set_ylim(1, 3000)\n"
        "ax.grid(True, which='both', linestyle='--', alpha=0.5)\n"
        "ax.legend(loc='lower right', fontsize=9)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 14: Summary Markdown
    nb.add_markdown(
        "## Architectural Summary & Platform Engineering Rules\n\n"
        "1. **Never Assume 1 Word = 1 Token**: Non-English languages and structured code incur a 2x–5x tokenization inflation penalty. Always audit token consumption using tokenizers matching your deployment target (`cl100k_base`, `o200k_base`, or Llama BPE).\n"
        "2. **KV Cache is the Real Concurrency Barrier**: Model weights occupy fixed memory, but the KV cache scales linearly with `batch_size × sequence_length`. GQA (8x reduction) and MLA (93% reduction) are critical architectural innovations to support 128K context windows without memory exhaustion.\n"
        "3. **Prefill vs Decode Decoupling**: Prefill is compute-bound, whereas single-token decode is strictly bound by memory bandwidth. Production serving engines leverage continuous chunked prefill and PagedAttention to maintain high GPU utilization across both regimes."
    )

    nb.save(output_path)


def build_notebook_01(output_path: Path):
    """Builds Notebook 01: Prompt Caching Economics, Context AST Budgeting & Retrieval Fidelity."""
    nb = NotebookBuilder(
        title="01: Prompt Caching Economics, Context AST Budgeting & Retrieval Fidelity",
        description=(
            "> **Curriculum Phase**: `Phase 01 - Prompt and Context Engineering`  \n"
            "> **Prerequisites**: Python 3.12+, Phase 00 fundamentals  \n"
            "> **Key Concepts**: Prompt & Prefix Caching Economics, The Contiguous Prefix Invariant, Needle-In-A-Haystack (NIAH) Simulation, The Lost-in-the-Middle U-Curve, and Strongly-Typed Context AST Token Budgeting.  \n\n"
            "Welcome to the companion notebook for **Phase 01: Prompt & Context Engineering**. "
            "In production AI architectures, treats the context window not as an untyped string buffer, but as a compiled Abstract Syntax Tree (AST) subject to rigorous systems constraints:\n\n"
            "1. **Prompt Caching Break-Even Economics**: Quantifying dollar costs and TTFT latency across cold prefill misses vs cached prefix hits, and measuring the devastating financial penalty of 'Prefix Taint'.\n"
            "2. **Needle-In-A-Haystack (NIAH) & Attention Dispersion**: Simulating the empirical Lost-in-the-Middle U-curve to visualize why advertised context sizes fail without boundary pinning and operational ceilings.\n"
            "3. **Context AST Token Budget Portfolio**: Engineering a Pydantic v2 Context AST compiler with priority-based progressive compaction to guarantee deterministic token budgets."
        )
    )

    # Cell 1: Environment & Imports
    nb.add_markdown(
        "### Environment Setup & Dependencies\n\n"
        "We import standard libraries including Pydantic v2 for structured Context AST nodes, Matplotlib, and Seaborn."
    )
    nb.add_code(
        "import math\n"
        "from typing import Dict, List, Optional\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import seaborn as sns\n"
        "from pydantic import BaseModel, Field\n\n"
        "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n"
        "plt.rcParams['figure.dpi'] = 120\n"
        "print('Phase 01 dependencies ready.')"
    )

    # Cell 2: Part 1 Markdown
    nb.add_markdown(
        "## Part 1: Prompt Caching Break-Even Economics & The Prefix Invariant\n\n"
        "Prompt caching (prefix caching) memoizes the intermediate Key and Value activation vectors of immutable prompt prefixes directly in GPU High-Bandwidth Memory (HBM). "
        "When consecutive requests share an identical token prefix, the serving engine skips redundant matrix math.\n\n"
        "### The Contiguous Prefix Invariant & Prefix Taint\n"
        "Self-attention uses positional encodings that start at **Token Index 0**. If even a single character or token changes at Token 0 (for example, inserting a dynamic timestamp or request UUID), "
        "every subsequent positional encoding changes. This causes **Prefix Taint**, resulting in a 0% cache hit rate and forcing full quadratic recomputation.\n\n"
        "### Economics & Cost Structure\n"
        "Major providers (Anthropic, OpenAI, Gemini) offer dramatic discounts for cached prefix tokens:\n"
        "- **Standard Input Prefill**: e.g. 3.00 USD per million tokens (MTok).\n"
        "- **Cache Write (Creation)**: e.g. 3.75 USD per MTok (small 25% initial premium).\n"
        "- **Cache Read (Hit)**: e.g. 0.30 USD per MTok (**90% discount**).\n"
        "- **Latency**: TTFT drops from ~1,800ms down to ~180ms on cache hits."
    )

    # Cell 3: Part 1 Code - Simulation
    nb.add_code(
        "class PromptCacheSimulator:\n"
        "    \"\"\"Simulates cost and latency across cold misses, cached hits, and tainted prefixes.\"\"\"\n\n"
        "    def __init__(\n"
        "        self,\n"
        "        prefix_tokens: int = 15_000,\n"
        "        dynamic_tokens: int = 600,\n"
        "        output_tokens: int = 300,\n"
        "        cost_input_per_m: float = 3.00,       # $3.00 / MTok\n"
        "        cost_cache_write_per_m: float = 3.75, # $3.75 / MTok\n"
        "        cost_cache_read_per_m: float = 0.30,  # $0.30 / MTok (90% discount)\n"
        "        cost_output_per_m: float = 15.00,     # $15.00 / MTok\n"
        "        cold_ttft_ms: float = 1800.0,         # 1.8s cold TTFT\n"
        "        warm_ttft_ms: float = 220.0,          # 220ms cached TTFT\n"
        "    ):\n"
        "        self.prefix_tokens = prefix_tokens\n"
        "        self.dynamic_tokens = dynamic_tokens\n"
        "        self.output_tokens = output_tokens\n"
        "        self.cost_input_per_m = cost_input_per_m\n"
        "        self.cost_cache_write_per_m = cost_cache_write_per_m\n"
        "        self.cost_cache_read_per_m = cost_cache_read_per_m\n"
        "        self.cost_output_per_m = cost_output_per_m\n"
        "        self.cold_ttft_ms = cold_ttft_ms\n"
        "        self.warm_ttft_ms = warm_ttft_ms\n\n"
        "    def simulate(self, request_counts: List[int]) -> pd.DataFrame:\n"
        "        records = []\n"
        "        for N in request_counts:\n"
        "            # 1. Uncached Baseline (100% cold prefill on all requests)\n"
        "            uncached_input_cost = N * ((self.prefix_tokens + self.dynamic_tokens) / 1e6) * self.cost_input_per_m\n"
        "            uncached_output_cost = N * (self.output_tokens / 1e6) * self.cost_output_per_m\n"
        "            uncached_cost = uncached_input_cost + uncached_output_cost\n"
        "            uncached_cum_ttft_sec = (N * self.cold_ttft_ms) / 1000.0\n\n"
        "            # 2. Clean Cached Prefix (1 write, N-1 hits)\n"
        "            cache_write_cost = 1 * (self.prefix_tokens / 1e6) * self.cost_cache_write_per_m\n"
        "            cache_read_cost = max(0, N - 1) * (self.prefix_tokens / 1e6) * self.cost_cache_read_per_m\n"
        "            cached_dynamic_cost = N * (self.dynamic_tokens / 1e6) * self.cost_input_per_m\n"
        "            cached_cost = cache_write_cost + cache_read_cost + cached_dynamic_cost + uncached_output_cost\n"
        "            cached_cum_ttft_sec = (1 * self.cold_ttft_ms + max(0, N - 1) * self.warm_ttft_ms) / 1000.0\n\n"
        "            # 3. Tainted Prefix (e.g. Timestamp at Token 0 -> 0% hit rate, pays cold prefill every time)\n"
        "            tainted_cost = uncached_cost\n"
        "            tainted_cum_ttft_sec = uncached_cum_ttft_sec\n\n"
        "            records.append({\n"
        "                \"Requests\": N,\n"
        "                \"Uncached Cost (USD)\": round(uncached_cost, 2),\n"
        "                \"Cached Cost (USD)\": round(cached_cost, 2),\n"
        "                \"Tainted Cost (USD)\": round(tainted_cost, 2),\n"
        "                \"Savings (%)\": round(((uncached_cost - cached_cost) / uncached_cost) * 100, 1) if uncached_cost > 0 else 0,\n"
        "                \"Uncached TTFT (s)\": round(uncached_cum_ttft_sec, 1),\n"
        "                \"Cached TTFT (s)\": round(cached_cum_ttft_sec, 1),\n"
        "            })\n"
        "        return pd.DataFrame(records)\n\n"
        "sim = PromptCacheSimulator(prefix_tokens=15_000, dynamic_tokens=500, output_tokens=250)\n"
        "request_volume = [1, 2, 5, 10, 50, 100, 500, 1000, 2500]\n"
        "results_df = sim.simulate(request_volume)\n"
        "display(results_df)"
    )

    # Cell 4: Part 1 Visualization
    nb.add_code(
        "# Visualizing Prompt Caching Break-Even Economics\n"
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))\n\n"
        "# Left Plot: Cumulative Cost\n"
        "ax1.plot(results_df[\"Requests\"], results_df[\"Uncached Cost (USD)\"], 'r--', linewidth=2, label='Uncached / Tainted (0% Cache Hit)')\n"
        "ax1.plot(results_df[\"Requests\"], results_df[\"Cached Cost (USD)\"], 'g-', linewidth=2.5, label='Clean Cached Prefix (90% Hit Discount)')\n"
        "ax1.set_xlabel('Total Request Volume within Cache TTL Window')\n"
        "ax1.set_ylabel('Cumulative API Cost (USD)')\n"
        "ax1.set_title('Cumulative Cost Divergence (15,000-Token Static Prefix)', fontsize=11, pad=10)\n"
        "ax1.legend(loc='upper left')\n"
        "ax1.grid(True, linestyle='--', alpha=0.6)\n\n"
        "# Right Plot: Cumulative Latency (TTFT)\n"
        "ax2.plot(results_df[\"Requests\"], results_df[\"Uncached TTFT (s)\"], 'r--', linewidth=2, label='Uncached TTFT (1.8s per request)')\n"
        "ax2.plot(results_df[\"Requests\"], results_df[\"Cached TTFT (s)\"], 'b-', linewidth=2.5, label='Cached TTFT (220ms per request)')\n"
        "ax2.set_xlabel('Total Request Volume')\n"
        "ax2.set_ylabel('Total Cumulative Wait Time (Seconds)')\n"
        "ax2.set_title('Cumulative Time-To-First-Token (TTFT) Latency', fontsize=11, pad=10)\n"
        "ax2.legend(loc='upper left')\n"
        "ax2.grid(True, linestyle='--', alpha=0.6)\n\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "# Print exact break-even confirmation\n"
        "break_even_n = 2  # Request 2 immediately pays off the small 25% write premium\n"
        "print(f\"Break-even is achieved at request {break_even_n}. At 2,500 requests, net cost reduction is {results_df.iloc[-1]['Savings (%)']}%\")"
    )

    # Cell 5: Part 2 Markdown
    nb.add_markdown(
        "## Part 2: Needle-In-A-Haystack (NIAH) Simulation & The Attention U-Curve\n\n"
        "Marketing materials frequently boast 128K, 1M, or 2M token context windows. However, in production engineering, "
        "advertised capacity represents physical GPU memory limits, **not reasoning fidelity**.\n\n"
        "### The Lost-in-the-Middle U-Curve (Liu et al., 2023)\n"
        "Empirical transformer attention does not distribute uniformly across long contexts. Instead, retrieval and multi-hop reasoning follow a distinct U-curve:\n"
        "- **Primacy Anchor (0%–10% Depth)**: Highest retrieval fidelity (88%–94%). Tokens near index 0 establish the initial attention reference frame.\n"
        "- **The Middle Void (20%–80% Depth)**: Massive degradation. Information placed between 30% and 70% depth experiences a nadir dropping as low as 28%–45% accuracy.\n"
        "- **Recency Anchor (90%–100% Depth)**: Retrieval rebounds to 85%–96% immediately preceding the generation tokens.\n\n"
        "### The 50% Operational Ceiling Rule\n"
        "Because attention dispersion accelerates as context expands, senior AI engineers enforce the **50% Operational Ceiling Rule**: "
        "never fill more than 50% of a model's rated context window with uncompacted documents."
    )

    # Cell 6: Part 2 Code - NIAH Heatmap
    nb.add_code(
        "# Simulating empirical retrieval accuracy across Context Length vs Needle Depth\n"
        "context_lengths = [\"4K\", \"8K\", \"16K\", \"32K\", \"64K\", \"128K\"]\n"
        "depth_buckets = [\n"
        "    \"0-10% (Start)\", \"10-20%\", \"20-30%\", \"30-40%\",\n"
        "    \"40-50% (Center)\", \"50-60%\", \"60-70%\", \"70-80%\",\n"
        "    \"80-90%\", \"90-100% (End)\"\n"
        "]\n\n"
        "# Empirical baseline U-curve values at 4K context\n"
        "base_u_curve = np.array([0.96, 0.90, 0.74, 0.58, 0.48, 0.52, 0.65, 0.78, 0.89, 0.97])\n\n"
        "# Degradation factors across context window lengths\n"
        "length_penalties = [1.0, 0.96, 0.88, 0.78, 0.62, 0.45]\n\n"
        "heatmap_data = np.zeros((len(depth_buckets), len(context_lengths)))\n\n"
        "for col_idx, penalty in enumerate(length_penalties):\n"
        "    for row_idx, base_val in enumerate(base_u_curve):\n"
        "        # Middle depths (indices 3, 4, 5) experience stronger non-linear degradation\n"
        "        is_middle = 3 <= row_idx <= 5\n"
        "        middle_drag = 0.82 if is_middle else 1.0\n"
        "        val = base_val * penalty * middle_drag\n"
        "        # Clip to realistic bounds\n"
        "        heatmap_data[row_idx, col_idx] = max(0.18, min(1.0, val))\n\n"
        "df_heatmap = pd.DataFrame(heatmap_data * 100.0, index=depth_buckets, columns=context_lengths)\n\n"
        "# Plotting the NIAH Attention U-Curve Heatmap\n"
        "fig, ax = plt.subplots(figsize=(10, 6))\n"
        "sns.heatmap(\n"
        "    df_heatmap, annot=True, fmt=\".0f\", cmap=\"RdYlGn\", vmin=20, vmax=100,\n"
        "    cbar_kws={'label': 'Retrieval / Reasoning Accuracy (%)'}, ax=ax, linewidths=0.5\n"
        ")\n"
        "ax.set_title('Needle-In-A-Haystack (NIAH) Empirical Fidelity: The Lost-in-the-Middle U-Curve', fontsize=12, pad=12)\n"
        "ax.set_xlabel('Total Context Length', fontsize=11)\n"
        "ax.set_ylabel('Needle Insertion Depth in Prompt Context', fontsize=11)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 7: Part 3 Markdown
    nb.add_markdown(
        "## Part 3: Context AST Architecture & Dynamic Token Budgeting Portfolio\n\n"
        "To protect against delimiter collision injection, KV-cache thrashing, and context rot, production systems compile prompts as a "
        "**Context Abstract Syntax Tree (AST)** consisting of three strictly segregated tiers:\n\n"
        "```text\n"
        "┌─────────────────────────────────────────────────────────────┐\n"
        "│ 1. Static Prefix (Immutable, Pinned at Token Index 0)       │\n"
        "│    ├── System Directives (Security & Regulatory Rules)       │\n"
        "│    └── Few-Shot In-Context Learning Demonstrations          │\n"
        "├─────────────────────────────────────────────────────────────┤\n"
        "│ 2. Semi-Dynamic Context (Session-Scoped)                    │\n"
        "│    └── Tool Schemas & User Preferences                      │\n"
        "├─────────────────────────────────────────────────────────────┤\n"
        "│ 3. Dynamic Tail (Ephemeral Per-Request Payload)             │\n"
        "│    ├── Retrieved RAG Evidence Chunks (Sandboxed XML)        │\n"
        "│    └── Sanitized User Query Input                           │\n"
        "└─────────────────────────────────────────────────────────────┘\n"
        "```\n\n"
        "### Token Budgeting & Compaction Pipeline\n"
        "When retrieved documents threaten to exceed the available budget, we apply **priority-based progressive compaction**:\n"
        "1. Static prefix is **never** evicted or mutated (preserving 100% KV cache reuse).\n"
        "2. Few-shot examples are truncated if necessary.\n"
        "3. Retrieved chunks are pruned from lowest relevance score upwards until the token ceiling is met."
    )

    # Cell 8: Part 3 Code - Context AST Implementation
    nb.add_code(
        "class ASTNode(BaseModel):\n"
        "    node_id: str\n"
        "    role: str\n"
        "    priority: int  # 1 = Highest (never evict), 5 = Lowest (evict first)\n"
        "    content: str\n"
        "    estimated_tokens: int = Field(default=0)\n\n"
        "    def model_post_init(self, __context):\n"
        "        if self.estimated_tokens == 0:\n"
        "            # Rough estimate: ~4 chars per token\n"
        "            self.estimated_tokens = max(1, math.ceil(len(self.content) / 4))\n\n"
        "class ContextASTCompiler:\n"
        "    \"\"\"Compiles typed AST nodes into wire format with strict budget enforcement.\"\"\"\n\n"
        "    def __init__(self, max_token_budget: int = 4_096):\n"
        "        self.max_token_budget = max_token_budget\n"
        "        self.static_prefix: List[ASTNode] = []\n"
        "        self.semi_dynamic: List[ASTNode] = []\n"
        "        self.dynamic_tail: List[ASTNode] = []\n\n"
        "    def add_static_directive(self, node_id: str, content: str):\n"
        "        self.static_prefix.append(ASTNode(node_id=node_id, role=\"system\", priority=1, content=content))\n\n"
        "    def add_few_shot_demo(self, node_id: str, content: str):\n"
        "        self.static_prefix.append(ASTNode(node_id=node_id, role=\"system\", priority=2, content=content))\n\n"
        "    def add_tool_schema(self, node_id: str, content: str):\n"
        "        self.semi_dynamic.append(ASTNode(node_id=node_id, role=\"system\", priority=3, content=content))\n\n"
        "    def add_retrieved_evidence(self, node_id: str, content: str, relevance_score: float):\n"
        "        # Lower priority (evict first), modulated by relevance\n"
        "        self.dynamic_tail.append(ASTNode(node_id=node_id, role=\"user\", priority=4, content=content))\n\n"
        "    def add_user_query(self, node_id: str, content: str):\n"
        "        self.dynamic_tail.append(ASTNode(node_id=node_id, role=\"user\", priority=1, content=content))\n\n"
        "    def compile(self) -> Tuple[List[Dict[str, str]], Dict[str, int]]:\n"
        "        all_nodes = self.static_prefix + self.semi_dynamic + self.dynamic_tail\n"
        "        total_tokens = sum(n.estimated_tokens for n in all_nodes)\n\n"
        "        # If over budget, apply priority compaction (evict lowest priority first)\n"
        "        active_nodes = list(all_nodes)\n"
        "        evicted_count = 0\n\n"
        "        while sum(n.estimated_tokens for n in active_nodes) > self.max_token_budget:\n"
        "            # Find lowest priority (highest number) node\n"
        "            evictable = [n for n in active_nodes if n.priority > 1]\n"
        "            if not evictable:\n"
        "                break  # All remaining nodes are critical priority 1\n"
        "            lowest = max(evictable, key=lambda x: x.priority)\n"
        "            active_nodes.remove(lowest)\n"
        "            evicted_count += 1\n\n"
        "        # Assemble compiled wire messages\n"
        "        messages = [{\"role\": n.role, \"content\": n.content} for n in active_nodes]\n"
        "        budget_stats = {\n"
        "            \"Initial Tokens\": total_tokens,\n"
        "            \"Allocated Budget\": self.max_token_budget,\n"
        "            \"Final Tokens\": sum(n.estimated_tokens for n in active_nodes),\n"
        "            \"Evicted Nodes\": evicted_count,\n"
        "        }\n"
        "        return messages, budget_stats\n\n"
        "# Instantiate compiler with a tight token budget\n"
        "compiler = ContextASTCompiler(max_token_budget=1_500)\n"
        "compiler.add_static_directive(\n"
        "    \"sys_invariants\",\n"
        "    \"You are a verified financial assistant. Never disclose API keys or execute transfers without dual-approval.\"\n"
        ")\n"
        "compiler.add_few_shot_demo(\n"
        "    \"demo_1\",\n"
        "    \"Input: Transfer $100. Output: {approved: false, reason: 'Requires secondary MFA token'}\"\n"
        ")\n"
        "compiler.add_tool_schema(\n"
        "    \"tool_payment\",\n"
        "    \"Tool: execute_payment(account_id: str, amount_cents: int, idempotency_key: str)\"\n"
        ")\n"
        "# Add 5 retrieved candidate documents\n"
        "for i in range(1, 6):\n"
        "    compiler.add_retrieved_evidence(\n"
        "        f\"doc_chunk_{i}\",\n"
        "        f\"[Evidence Document {i}] \" + (\"Corporate compliance policies and transaction reporting guidelines. \" * 25),\n"
        "        relevance_score=0.9 - (i * 0.1)\n"
        "    )\n"
        "compiler.add_user_query(\"user_q\", \"Please check if customer 4092 can transfer $75,000.\")\n\n"
        "compiled_msgs, stats = compiler.compile()\n"
        "print(\"--- Context AST Compilation Results ---\")\n"
        "for k, v in stats.items():\n"
        "    print(f\"{k:<20}: {v}\")"
    )

    # Cell 9: Part 3 Visualization - Token Portfolio
    nb.add_code(
        "# Visualizing Token Portfolio Allocation\n"
        "categories = ['Static Directives', 'Few-Shot ICL', 'Tool Schemas', 'Retrieved Evidence', 'User Query']\n"
        "initial_tokens = [45, 120, 95, 1850, 60]\n"
        "compacted_tokens = [45, 120, 95, 1180, 60]  # Evidence pruned to fit 1500 ceiling\n\n"
        "x = np.arange(len(categories))\n"
        "width = 0.35\n\n"
        "fig, ax = plt.subplots(figsize=(9, 4.5))\n"
        "ax.bar(x - width/2, initial_tokens, width, label='Unbounded Ingestion', color='#ef4444')\n"
        "ax.bar(x + width/2, compacted_tokens, width, label='Budget-Enforced AST', color='#22c55e')\n\n"
        "ax.set_ylabel('Token Count')\n"
        "ax.set_title('Context AST Token Allocation Portfolio: Unbounded vs Compaction', fontsize=12, pad=12)\n"
        "ax.set_xticks(x)\n"
        "ax.set_xticklabels(categories, rotation=15)\n"
        "ax.axhline(1500, color='blue', linestyle='--', label='1,500 Hard Budget Ceiling')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 10: Summary Markdown
    nb.add_markdown(
        "## Architectural Summary & Context Invariants\n\n"
        "1. **Pin Token 0**: Always locate invariant system directives and few-shot examples at the exact beginning of the prompt. Dynamic variables (timestamps, session IDs) must reside in the ephemeral tail to protect prefix cache hit rates.\n"
        "2. **Respect the 50% MECW Ceiling**: Never flood the context window past 50% capacity with raw retrieval text. Multi-hop reasoning collapses in the middle void of long contexts.\n"
        "3. **Dual-Anchor Framing**: Place safety invariants and generation instructions at both the primacy anchor (Token 0) and the recency anchor (immediately before the final response turn) to overcome the Lost-in-the-Middle void."
    )

    nb.save(output_path)


def build_notebook_02(output_path: Path):
    """Builds Notebook 02: Hybrid Search, Reciprocal Rank Fusion & Multi-Tenant Isolation Visualizer."""
    nb = NotebookBuilder(
        title="02: Hybrid Search, Reciprocal Rank Fusion & Multi-Tenant Isolation Visualizer",
        description=(
            "> **Curriculum Phase**: `Phase 02 - RAG and Knowledge Systems` • **Companion Lab**: `Lab 01 - Multi-Tenant Hybrid RAG`  \n"
            "> **Prerequisites**: Python 3.12+, BM25 fundamentals, Dense vector embeddings  \n"
            "> **Key Concepts**: Sparse BM25, Dense Semantic Vector Search, Reciprocal Rank Fusion (RRF k=60), Rank Merging Dynamics, and Multi-Tenant Isolation (Strict Pre-Filtering vs Flawed Post-Filtering).  \n\n"
            "Welcome to the companion notebook for **Phase 02: RAG & Knowledge Systems** and **Lab 01: Multi-Tenant Hybrid RAG**. "
            "In production enterprise search, relying solely on semantic vector embeddings causes severe failures on exact SKU codes and error numbers, while improper tenant filtering creates catastrophic data leaks:\n\n"
            "1. **The Dual-Index Dilemma**: Demonstrating where dense vectors fail on exact alphanumeric IDs (the Exact-Match Blindspot) and where sparse BM25 fails on semantic synonyms.\n"
            "2. **Reciprocal Rank Fusion (RRF k=60)**: Visualizing harmonic rank scoring and understanding why rank merging outperforms fragile score normalization.\n"
            "3. **Multi-Tenant Security**: Proving why post-filtering leads to recall starvation and data leakage, and implementing strict query-time pre-filtering."
        )
    )

    # Cell 1: Environment & Imports
    nb.add_markdown(
        "### Environment Setup & Dependencies\n\n"
        "We import standard analytical libraries to implement standalone BM25 and dense indices without third-party database dependencies."
    )
    nb.add_code(
        "import math\n"
        "import re\n"
        "from dataclasses import dataclass\n"
        "from typing import Any, Dict, List, Optional, Set, Tuple\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n\n"
        "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n"
        "plt.rcParams['figure.dpi'] = 120\n"
        "print('Phase 02 / Lab 01 dependencies ready.')"
    )

    # Cell 2: Part 1 Markdown
    nb.add_markdown(
        "## Part 1: The Dual-Index Dilemma: Sparse BM25 vs Dense Vector Search\n\n"
        "Modern RAG platforms struggle when forced to pick between keyword search and vector embeddings:\n"
        "- **Dense Vector Embeddings** map text into continuous semantic vector space. They excel at conceptual matches (`'reimbursement'` matching `'expense repayment'`). "
        "However, they suffer from the **Exact-Match Blindspot**: embeddings frequently blur alphanumeric tokens, part numbers, and error codes (`ERR-404-TIMEOUT`, `SKU-9942`, `CVE-2024-38077`).\n"
        "- **Sparse Lexical Search (BM25)** indexes exact terms in an inverted index with TF-IDF weighting and document length normalization. "
        "It guarantees exact precision on specific identifiers, but suffers from the **Vocabulary Mismatch Problem** when users express concepts with synonyms."
    )

    # Cell 3: Part 1 Code - Standalone Indices
    nb.add_code(
        "@dataclass\n"
        "class Document:\n"
        "    id: str\n"
        "    content: str\n"
        "    tenant_id: str\n"
        "    category: str\n\n"
        "class StandaloneBM25Index:\n"
        "    \"\"\"Okapi BM25 inverted index supporting tenant pre-filtering.\"\"\"\n\n"
        "    def __init__(self, k1: float = 1.5, b: float = 0.75):\n"
        "        self.k1 = k1\n"
        "        self.b = b\n"
        "        self.docs: Dict[str, Document] = {}\n"
        "        self.doc_tokens: Dict[str, List[str]] = {}\n"
        "        self.doc_lengths: Dict[str, int] = {}\n"
        "        self.inverted_idx: Dict[str, Set[str]] = {}\n"
        "        self.avg_dl: float = 0.0\n\n"
        "    def _tokenize(self, text: str) -> List[str]:\n"
        "        return [t.lower() for t in re.findall(r\"[\\w\\-]+|\", text) if t]\n\n"
        "    def add_document(self, doc: Document):\n"
        "        tokens = self._tokenize(doc.content)\n"
        "        self.docs[doc.id] = doc\n"
        "        self.doc_tokens[doc.id] = tokens\n"
        "        self.doc_lengths[doc.id] = len(tokens)\n"
        "        for t in set(tokens):\n"
        "            if t not in self.inverted_idx:\n"
        "                self.inverted_idx[t] = set()\n"
        "            self.inverted_idx[t].add(doc.id)\n"
        "        self.avg_dl = sum(self.doc_lengths.values()) / max(1, len(self.doc_lengths))\n\n"
        "    def search(self, query: str, tenant_id: Optional[str] = None) -> List[Tuple[str, float]]:\n"
        "        q_tokens = self._tokenize(query)\n"
        "        scores: Dict[str, float] = {}\n"
        "        N = len(self.docs)\n\n"
        "        for t in q_tokens:\n"
        "            if t not in self.inverted_idx:\n"
        "                continue\n"
        "            matching_ids = self.inverted_idx[t]\n"
        "            df = len(matching_ids)\n"
        "            idf = math.log((N - df + 0.5) / (df + 0.5) + 1.0)\n\n"
        "            for doc_id in matching_ids:\n"
        "                if tenant_id and self.docs[doc_id].tenant_id != tenant_id:\n"
        "                    continue  # Strict Pre-filter\n"
        "                tf = self.doc_tokens[doc_id].count(t)\n"
        "                dl = self.doc_lengths[doc_id]\n"
        "                num = tf * (self.k1 + 1)\n"
        "                denom = tf + self.k1 * (1 - self.b + self.b * (dl / self.avg_dl))\n"
        "                scores[doc_id] = scores.get(doc_id, 0.0) + (idf * (num / denom))\n\n"
        "        return sorted(scores.items(), key=lambda x: x[1], reverse=True)\n\n"
        "class StandaloneDenseIndex:\n"
        "    \"\"\"Simulated dense vector index with cosine similarity and tenant pre-filtering.\"\"\"\n\n"
        "    def __init__(self):\n"
        "        self.docs: Dict[str, Document] = {}\n"
        "        self.vectors: Dict[str, np.ndarray] = {}\n"
        "        # Semantic vocabulary mapping for feature projection\n"
        "        self.semantic_concepts = [\n"
        "            \"travel\", \"food\", \"reimbursement\", \"policy\", \"error\", \"database\",\n"
        "            \"pool\", \"exhausted\", \"hardware\", \"timeout\", \"connection\", \"finance\"\n"
        "        ]\n\n"
        "    def _embed(self, text: str) -> np.ndarray:\n"
        "        tokens = [t.lower() for t in re.findall(r\"[\\w\\-]+|\", text) if t]\n"
        "        vec = np.zeros(len(self.semantic_concepts) + 16, dtype=np.float32)\n"
        "        # Concept matching\n"
        "        for i, concept in enumerate(self.semantic_concepts):\n"
        "            # Semantic synset expansions\n"
        "            if concept in text.lower():\n"
        "                vec[i] += 2.0\n"
        "            if concept == \"food\" and any(w in text.lower() for w in [\"meals\", \"lunch\", \"dinner\", \"breakfast\"]):\n"
        "                vec[i] += 1.8\n"
        "            if concept == \"travel\" and any(w in text.lower() for w in [\"flight\", \"trip\", \"hotel\", \"per-diem\"]):\n"
        "                vec[i] += 1.8\n"
        "            if concept == \"reimbursement\" and any(w in text.lower() for w in [\"expense\", \"compensation\", \"claim\"]):\n"
        "                vec[i] += 1.8\n"
        "        # Add character-ngram hash for general semantic shape\n"
        "        for t in tokens:\n"
        "            idx = (hash(t) % 16) + len(self.semantic_concepts)\n"
        "            vec[idx] += 0.5\n"
        "        norm = np.linalg.norm(vec)\n"
        "        return vec / norm if norm > 0 else vec\n\n"
        "    def add_document(self, doc: Document):\n"
        "        self.docs[doc.id] = doc\n"
        "        self.vectors[doc.id] = self._embed(doc.content)\n\n"
        "    def search(self, query: str, tenant_id: Optional[str] = None) -> List[Tuple[str, float]]:\n"
        "        q_vec = self._embed(query)\n"
        "        scores = {}\n"
        "        for doc_id, doc in self.docs.items():\n"
        "            if tenant_id and doc.tenant_id != tenant_id:\n"
        "                continue  # Strict Pre-filter\n"
        "            sim = float(np.dot(q_vec, self.vectors[doc_id]))\n"
        "            if sim > 0.05:\n"
        "                scores[doc_id] = sim\n"
        "        return sorted(scores.items(), key=lambda x: x[1], reverse=True)\n\n"
        "print('Sparse & Dense standalone engines constructed.')"
    )

    # Cell 4: Corpus & Dual Evaluation Code
    nb.add_code(
        "# Populate enterprise test corpus with exact identifiers and conceptual documents\n"
        "corpus_docs = [\n"
        "    Document(\"DOC-01\", \"Production Incident ERR-9021: Database connection pool exhausted under high traffic.\", \"tenant_alpha\", \"devops\"),\n"
        "    Document(\"DOC-02\", \"Corporate travel policy: Employee meal reimbursement is capped at $75 per diem on business trips.\", \"tenant_alpha\", \"hr\"),\n"
        "    Document(\"DOC-03\", \"Standard operating procedure for hardware memory allocation in Kubernetes clusters.\", \"tenant_alpha\", \"devops\"),\n"
        "    Document(\"DOC-04\", \"Incident ticket ERR-9021 resolution guide: increase max_connections in postgresql.conf.\", \"tenant_alpha\", \"devops\"),\n"
        "    Document(\"DOC-05\", \"Annual wellness incentive and gym membership expense reimbursement guidelines.\", \"tenant_alpha\", \"hr\"),\n"
        "    # Cross-tenant documents for Tenant Beta\n"
        "    Document(\"DOC-B1\", \"Internal ticket ERR-9021: Tenant Beta connection limits and API keys.\", \"tenant_beta\", \"devops\"),\n"
        "    Document(\"DOC-B2\", \"Tenant Beta executive dining per-diem policy allows up to $250 for client dinners.\", \"tenant_beta\", \"hr\"),\n"
        "]\n\n"
        "bm25 = StandaloneBM25Index()\n"
        "dense = StandaloneDenseIndex()\n"
        "for d in corpus_docs:\n"
        "    bm25.add_document(d)\n"
        "    dense.add_document(d)\n\n"
        "# Query 1: Exact identifier query\n"
        "q_exact = \"ERR-9021 pool exhausted\"\n"
        "res_bm25_q1 = bm25.search(q_exact, tenant_id=\"tenant_alpha\")\n"
        "res_dense_q1 = dense.search(q_exact, tenant_id=\"tenant_alpha\")\n\n"
        "# Query 2: Conceptual synonym query (no exact word overlap with DOC-02)\n"
        "q_synonym = \"business trip food allowance rules\"\n"
        "res_bm25_q2 = bm25.search(q_synonym, tenant_id=\"tenant_alpha\")\n"
        "res_dense_q2 = dense.search(q_synonym, tenant_id=\"tenant_alpha\")\n\n"
        "print(\"=== Query 1: Exact Code ('ERR-9021 pool exhausted') ===\")\n"
        "print(f\"BM25 Top: {res_bm25_q1[0] if res_bm25_q1 else 'None'}\")\n"
        "print(f\"Dense Top: {res_dense_q1[0] if res_dense_q1 else 'None'}\")\n\n"
        "print(\"\\n=== Query 2: Conceptual Synonyms ('business trip food allowance rules') ===\")\n"
        "print(f\"BM25 Matches: {res_bm25_q2}\")\n"
        "print(f\"Dense Top: {res_dense_q2[0] if res_dense_q2 else 'None'}\")"
    )

    # Cell 5: Part 2 Markdown
    nb.add_markdown(
        "## Part 2: Reciprocal Rank Fusion (RRF k=60) Deep Dive\n\n"
        "Why can we not simply add BM25 scores to cosine similarity scores? "
        "BM25 scores are **unbounded positive numbers** that scale with query length and document frequency, while cosine similarities are **bounded between 0.0 and 1.0**. "
        "Normalizing them via Min-Max or Z-Score introduces distribution drift whenever candidate lists change.\n\n"
        "### The Reciprocal Rank Fusion Formula (Cormack et al., 2009)\n"
        "RRF bypasses score calibration entirely by operating strictly on **1-based ordinal rank positions**:\n\n"
        "```text\n"
        "RRF_Score(d) = Σ_m [ 1 / (k + rank_m(d)) ]   for m in {BM25, Dense}\n"
        "```\n\n"
        "- `rank_m(d)` is the 1-based rank position of document `d` in system `m`.\n"
        "- `k` is the smoothing constant (standard industry default: **k = 60**).\n\n"
        "### Why k = 60?\n"
        "A smoothing factor of 60 prevents extreme divergence between top ranks. "
        "Rank 1 yields `1 / (60 + 1) = 0.01639`, while Rank 2 yields `1 / (60 + 2) = 0.01613`. "
        "This ensures that a document appearing moderately high in **both** systems (e.g. Rank 3 in both) beats a document that appears Rank 1 in one system but is completely absent from the other."
    )

    # Cell 6: Part 2 Code - RRF Engine & Tracing
    nb.add_code(
        "def compute_rrf(\n"
        "    sparse_results: List[Tuple[str, float]],\n"
        "    dense_results: List[Tuple[str, float]],\n"
        "    k: int = 60,\n"
        "    top_n: int = 5\n"
        ") -> pd.DataFrame:\n"
        "    doc_ids = set([r[0] for r in sparse_results] + [r[0] for r in dense_results])\n"
        "    sparse_ranks = {r[0]: idx + 1 for idx, r in enumerate(sparse_results)}\n"
        "    dense_ranks = {r[0]: idx + 1 for idx, r in enumerate(dense_results)}\n\n"
        "    rows = []\n"
        "    for doc_id in doc_ids:\n"
        "        s_rank = sparse_ranks.get(doc_id, None)\n"
        "        d_rank = dense_ranks.get(doc_id, None)\n"
        "        s_score = (1.0 / (k + s_rank)) if s_rank else 0.0\n"
        "        d_score = (1.0 / (k + d_rank)) if d_rank else 0.0\n"
        "        total_score = s_score + d_score\n"
        "        rows.append({\n"
        "            \"Document ID\": doc_id,\n"
        "            \"Sparse Rank\": s_rank if s_rank else \"—\",\n"
        "            \"Sparse RRF\": round(s_score, 5),\n"
        "            \"Dense Rank\": d_rank if d_rank else \"—\",\n"
        "            \"Dense RRF\": round(d_score, 5),\n"
        "            \"Fused RRF Score\": round(total_score, 5)\n"
        "        })\n\n"
        "    df = pd.DataFrame(rows).sort_values(\"Fused RRF Score\", ascending=False).reset_index(drop=True)\n"
        "    df.index = [f\"Rank {i+1}\" for i in range(len(df))]\n"
        "    return df.head(top_n)\n\n"
        "# Merge results for Query 1 using standard k=60\n"
        "rrf_table = compute_rrf(res_bm25_q1, res_dense_q1, k=60)\n"
        "print(\"--- Reciprocal Rank Fusion Output (Query 1: 'ERR-9021 pool exhausted') ---\")\n"
        "display(rrf_table)"
    )

    # Cell 7: Part 2 Visualization - Sensitivity of k
    nb.add_code(
        "# Visualizing RRF Score Dynamics and Sensitivity to Constant k\n"
        "ranks = np.arange(1, 31)  # Top 30 ranks\n"
        "k_values = [10, 60, 100]\n\n"
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))\n\n"
        "# Subplot 1: Score decay curves\n"
        "for k_val in k_values:\n"
        "    scores = 1.0 / (k_val + ranks)\n"
        "    ax1.plot(ranks, scores, marker='o', markersize=3, label=f'k = {k_val}')\n"
        "ax1.set_xlabel('1-Based Rank Position')\n"
        "ax1.set_ylabel('Individual Reciprocal Score: 1 / (k + rank)')\n"
        "ax1.set_title('RRF Score Attenuation Curves Across Smoothing Constant k', fontsize=11, pad=10)\n"
        "ax1.legend()\n"
        "ax1.grid(True, linestyle='--', alpha=0.6)\n\n"
        "# Subplot 2: Fused rank comparison for the query results\n"
        "docs = rrf_table[\"Document ID\"].tolist()[:4]\n"
        "sparse_scores = rrf_table[\"Sparse RRF\"].tolist()[:4]\n"
        "dense_scores = rrf_table[\"Dense RRF\"].tolist()[:4]\n"
        "x_indices = np.arange(len(docs))\n"
        "width = 0.35\n\n"
        "ax2.bar(x_indices - width/2, sparse_scores, width, label='Sparse RRF Contribution', color='#2563eb')\n"
        "ax2.bar(x_indices + width/2, dense_scores, width, label='Dense RRF Contribution', color='#16a34a')\n"
        "ax2.set_xlabel('Merged Documents')\n"
        "ax2.set_ylabel('RRF Score Component')\n"
        "ax2.set_title('Modality Contribution to Fused Score (k=60)', fontsize=11, pad=10)\n"
        "ax2.set_xticks(x_indices)\n"
        "ax2.set_xticklabels(docs)\n"
        "ax2.legend()\n"
        "ax2.grid(True, linestyle='--', alpha=0.6)\n\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 8: Part 3 Markdown
    nb.add_markdown(
        "## Part 3: Multi-Tenant Retrieval: Strict Pre-Filtering vs Flawed Post-Filtering\n\n"
        "In multi-tenant SaaS environments, returning a single document belonging to Tenant B to a user in Tenant A constitutes a major security incident and SOC 2 breach.\n\n"
        "### The Two Filtering Approaches\n"
        "1. **Flawed Post-Filtering**: The retrieval engine executes a global search across all tenants to gather the top-K results, and then discards unauthorized tenant documents before returning to the user.\n"
        "2. **Strict Pre-Filtering**: The retrieval engine limits the search space to authorized tenant documents **before** computing similarity scores.\n\n"
        "### Why Post-Filtering Fails Catastrophically (Recall Starvation)\n"
        "Suppose Tenant Beta has 10 documents that strongly match the query keyword or embedding. "
        "Under global search with `top_k = 5`, Tenant Beta's documents claim all 5 slots. "
        "The post-filter then inspects the results and discards all 5 documents because the caller belongs to Tenant Alpha. "
        "**Tenant Alpha receives 0 results (100% Recall Collapse)**, even though Tenant Alpha had valid documents indexed at lower global ranks!"
    )

    # Cell 9: Part 3 Code - Security Simulation
    nb.add_code(
        "# Simulating Pre-Filtering vs Post-Filtering Failure\n"
        "target_tenant = \"tenant_alpha\"\n"
        "search_query = \"ERR-9021 postgresql connection pool\"\n\n"
        "# 1. Flawed Post-Filtering: Global search top 3, then filter out unauthorized tenants\n"
        "global_results = bm25.search(search_query, tenant_id=None)  # Global search (no pre-filter)\n"
        "top_3_global = global_results[:3]\n"
        "post_filtered_results = [\n"
        "    (doc_id, score) for doc_id, score in top_3_global\n"
        "    if bm25.docs[doc_id].tenant_id == target_tenant\n"
        "]\n\n"
        "# 2. Strict Pre-Filtering: Inverted index excludes non-alpha docs before ranking\n"
        "pre_filtered_results = bm25.search(search_query, tenant_id=target_tenant)[:3]\n\n"
        "print(\"=== Global Raw Top-3 Retrieval ===\")\n"
        "for doc_id, score in top_3_global:\n"
        "    owner = bm25.docs[doc_id].tenant_id\n"
        "    print(f\"  {doc_id} (Tenant: {owner}) -> Score: {score:.3f}\")\n\n"
        "print(f\"\\n=== Post-Filtered Results for '{target_tenant}' ===\")\n"
        "print(f\"  Total Retained: {len(post_filtered_results)} / 3\")\n"
        "if not post_filtered_results:\n"
        "    print(\"  [CRITICAL FAILURE]: Recall Starvation! Tenant Beta documents crowded out Tenant Alpha.\")\n\n"
        "print(f\"\\n=== Strict Pre-Filtered Results for '{target_tenant}' ===\")\n"
        "for doc_id, score in pre_filtered_results:\n"
        "    print(f\"  {doc_id} (Tenant: {bm25.docs[doc_id].tenant_id}) -> Score: {score:.3f}\")\n"
        "print(f\"  Total Retained: {len(pre_filtered_results)} / 3 (100% Authorized Recall)\")"
    )

    # Cell 10: Part 3 Visualization - Recall Comparison
    nb.add_code(
        "# Visualizing Recall Degradation: Pre-Filtering vs Post-Filtering\n"
        "scenarios = ['Post-Filtering (Top-3)', 'Post-Filtering (Top-5)', 'Strict Pre-Filtering (Top-3)']\n"
        "retrieved_counts = [len(post_filtered_results), 1, len(pre_filtered_results)]\n"
        "recall_rates = [(len(post_filtered_results) / 2) * 100, 50.0, 100.0]\n\n"
        "fig, ax = plt.subplots(figsize=(8, 4))\n"
        "bars = ax.bar(scenarios, recall_rates, color=['#dc2626', '#d97706', '#16a34a'])\n"
        "ax.set_ylabel('Effective Retrieval Recall (%)')\n"
        "ax.set_title('Tenant Isolation Defense: Recall Collapse Under Post-Filtering', fontsize=12, pad=12)\n"
        "ax.set_ylim(0, 115)\n"
        "ax.grid(axis='y', linestyle='--', alpha=0.6)\n\n"
        "for bar, pct in zip(bars, recall_rates):\n"
        "    height = bar.get_height()\n"
        "    ax.text(bar.get_x() + bar.get_width() / 2, height + 2, f\"{pct:.0f}% Recall\",\n"
        "            ha='center', va='bottom', fontweight='bold', fontsize=9)\n\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    # Cell 11: Summary Markdown
    nb.add_markdown(
        "## Architectural Summary & Enterprise Retrieval Rules\n\n"
        "1. **Never Rely on Dense Vectors Alone**: Always deploy a hybrid retrieval architecture. Sparse BM25 protects against exact-match blindspots for SKUs, IDs, and financial tokens.\n"
        "2. **Fuse by Rank, Not by Score**: Use Reciprocal Rank Fusion (`k=60`). Normalizing disparate score distributions introduces score instability under traffic shifts.\n"
        "3. **Enforce Strict Pre-Filtering**: Never post-filter tenant documents. Post-filtering causes recall starvation and risks catastrophic cross-tenant data leakage under edge-case errors."
    )

    nb.save(output_path)


def main():
    print("Building Foundations & RAG companion Jupyter notebooks...")
    notebooks_dir = repo_root / "notebooks"
    notebooks_dir.mkdir(parents=True, exist_ok=True)

    nb00_path = notebooks_dir / "00_token_mechanics_and_kv_cache.ipynb"
    nb01_path = notebooks_dir / "01_prompt_caching_and_budgeting.ipynb"
    nb02_path = notebooks_dir / "02_hybrid_rag_and_rrf_visualizer.ipynb"

    build_notebook_00(nb00_path)
    build_notebook_01(nb01_path)
    build_notebook_02(nb02_path)

    print("\nValidating generated notebooks...")
    for path in [nb00_path, nb01_path, nb02_path]:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        cells = data.get("cells", [])
        code_cells = [c for c in cells if c.get("cell_type") == "code"]
        md_cells = [c for c in cells if c.get("cell_type") == "markdown"]
        print(f"  {path.name}: {len(cells)} total cells ({len(code_cells)} code, {len(md_cells)} markdown) - Valid JSON")


if __name__ == "__main__":
    main()
