"""
generate_nb_06.py
=============================================================================
Generator script for:
notebooks/06_eval_flywheel_and_trace_trees.ipynb
(Lab 05 & Phase 06 companion: AI Observability, OpenTelemetry GenAI Tracing,
Trace Waterfalls, and LLM-as-a-Judge Evaluation Flywheel)
=============================================================================
"""

import sys
from pathlib import Path

# Ensure repo root is in python path
repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root))

from scripts.nb_helper import NotebookBuilder


def build_notebook_06():
    title = "06: GenAI Evaluation Flywheel, OpenTelemetry Distributed Tracing & Waterfall Visualizations"
    description = (
        "> **Lab 05 & Phase 06 Companion Notebook**  \n"
        "> **Topics**: OpenTelemetry GenAI Semantic Conventions (`gen_ai.*`), "
        "Hierarchical Span Trace Trees, Interactive Matplotlib Waterfall Timelines, "
        "LLM-as-a-Judge Harness (Groundedness & Faithfulness), Confusion Matrices & Threshold Tuning."
    )

    nb = NotebookBuilder(title, description)

    # -------------------------------------------------------------------------
    # Cell 1: Conceptual Overview & Architectural Context
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 1. Architectural Foundations: The Observability & Evaluation Flywheel\n\n"
        "In classical microservices, distributed tracing instruments HTTP endpoints, database queries, "
        "and gRPC hops. However, in generative AI and autonomous agent systems, standard APM tools leave "
        "engineering teams blind to three critical operational realities:\n\n"
        "1. **The Latency Black Box**: When an agentic reasoning loop takes 7.2 seconds, where did the time go? "
        "Was it spent waiting on hybrid dense/sparse vector retrieval (HNSW), an external Model Context Protocol "
        "(MCP) tool invocation, or autoregressive LLM token generation?\n"
        "2. **Token Accounting & Cost Attribution**: Without standard semantic attributes recording "
        "`gen_ai.request.model`, prompt tokens, and completion tokens on every span, platform teams cannot "
        "attribute spend to specific users, tenants, or autonomous agent steps.\n"
        "3. **The Dual Evaluation Loop**: Online telemetry (traces, latency, token budgets) and offline evaluation "
        "(LLM-as-a-judge, groundedness, faithfulness) must form a closed flywheel: production anomalies feed the "
        "golden evaluation dataset, and automated gates prevent regressions in deployment.\n\n"
        "```text\n"
        "+-----------------------------------------------------------------------------------+\n"
        "|                    CLOSED-LOOP GenAI EVALUATION & OBSERVABILITY                   |\n"
        "+-----------------------------------------------------------------------------------+\n"
        "|                                                                                   |\n"
        "|   [User Prompt] ---> [GenAITracer: Root Span (agent_turn_execution)]              |\n"
        "|                              |                                                    |\n"
        "|       +----------------------+----------------------+                             |\n"
        "|       |                      |                      |                             |\n"
        "|   [Child Span:          [Child Span:          [Child Span:                        |\n"
        "|    hybrid_retrieval]     model_inference]      mcp_tool_execution]                |\n"
        "|       |                      |                      |                             |\n"
        "|       +----------------------+----------------------+                             |\n"
        "|                              |                                                    |\n"
        "|                     [Trace Waterfall]                                             |\n"
        "|                              |                                                    |\n"
        "|            +-----------------+-----------------+                                  |\n"
        "|            |                                   |                                  |\n"
        "|            v                                   v                                  |\n"
        "|     [Online Telemetry]                 [Offline Eval Harness]                     |\n"
        "|     - Latency P50/P95                  - Groundedness Judge                       |\n"
        "|     - Token Accumulation               - Faithfulness Scoring                     |\n"
        "|     - Cost Attribution                 - Confusion Matrix / F1                    |\n"
        "|            |                                   |                                  |\n"
        "|            +-----------------> [CI/CD Gate] <--+                                  |\n"
        "+-----------------------------------------------------------------------------------+\n"
        "```\n\n"
        "In this notebook, we implement the CNCF/OpenTelemetry GenAI semantic conventions, build an interactive "
        "trace waterfall Gantt chart in Matplotlib, and develop a complete LLM-as-a-judge evaluation harness with "
        "confusion matrices and threshold optimization."
    )

    # -------------------------------------------------------------------------
    # Cell 2: Environment Setup & Core Imports
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 2. Environment Setup & Core Imports\n\n"
        "We import standard scientific and visualization libraries (`matplotlib`, `seaborn`, `pandas`, `numpy`) "
        "along with Python's typing and dataclass primitives. We also configure high-resolution plotting styles."
    )

    nb.add_code(
        "import os\n"
        "import sys\n"
        "import time\n"
        "import uuid\n"
        "import json\n"
        "import math\n"
        "from dataclasses import dataclass, field\n"
        "from typing import Any, Dict, List, Optional, Tuple\n"
        "\n"
        "import matplotlib.pyplot as plt\n"
        "import matplotlib.patches as mpatches\n"
        "import matplotlib.lines as mlines\n"
        "import seaborn as sns\n"
        "import pandas as pd\n"
        "import numpy as np\n"
        "\n"
        "# Configure clean visualization aesthetics\n"
        "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n"
        "plt.rcParams['font.sans-serif'] = 'DejaVu Sans'\n"
        "plt.rcParams['axes.edgecolor'] = '#cbd5e1'\n"
        "plt.rcParams['axes.linewidth'] = 1.0\n"
        "plt.rcParams['figure.autolayout'] = True\n"
        "\n"
        "print('Libraries loaded successfully. Visual plotting configured.')"
    )

    # -------------------------------------------------------------------------
    # Cell 3: OpenTelemetry GenAI Semantic Conventions Implementation
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 3. Implementing OpenTelemetry GenAI Semantic Conventions\n\n"
        "The OpenTelemetry community defines standardized attribute namespaces for Generative AI systems (`gen_ai.*`):\n\n"
        "| Attribute Name | Type | Description | Example |\n"
        "| :--- | :--- | :--- | :--- |\n"
        "| `gen_ai.system` | string | Provider or runtime system name | `'anthropic'`, `'openai'`, `'agent-forge'` |\n"
        "| `gen_ai.request.model` | string | Target model identifier | `'claude-3-7-sonnet'`, `'gpt-4o'` |\n"
        "| `gen_ai.usage.prompt_tokens` | int | Number of input / prompt tokens consumed | `342` |\n"
        "| `gen_ai.usage.completion_tokens` | int | Number of generated completion tokens | `89` |\n"
        "| `gen_ai.operation.name` | string | Logical operation performed | `'chat'`, `'retrieval'`, `'tool_execution'` |\n"
        "| `gen_ai.tool.name` | string | Name of the tool invoked by the agent | `'check_order_status'`, `'issue_refund'` |\n"
        "| `idempotency_key` | string | Deduplication token for stateful side-effects | `'tx_refund_9182'` |\n\n"
        "Below is a self-contained, enterprise-grade `GenAISpan` and `GenAITracer` implementation matching `agent-forge`."
    )

    nb.add_code(
        "@dataclass\n"
        "class GenAISpan:\n"
        "    \"\"\"\n"
        "    Represents a distributed trace span adhering to OpenTelemetry GenAI semantic conventions.\n"
        "    \"\"\"\n"
        "    name: str\n"
        "    trace_id: str = field(default_factory=lambda: f\"trace_{uuid.uuid4().hex[:12]}\")\n"
        "    span_id: str = field(default_factory=lambda: f\"span_{uuid.uuid4().hex[:8]}\")\n"
        "    parent_span_id: Optional[str] = None\n"
        "    start_time: float = field(default_factory=time.time)\n"
        "    end_time: Optional[float] = None\n"
        "    duration_ms: float = 0.0\n"
        "    attributes: Dict[str, Any] = field(default_factory=dict)\n"
        "    events: List[Dict[str, Any]] = field(default_factory=list)\n"
        "    children: List['GenAISpan'] = field(default_factory=list)\n"
        "\n"
        "    def set_attribute(self, key: str, value: Any) -> 'GenAISpan':\n"
        "        self.attributes[key] = value\n"
        "        return self\n"
        "\n"
        "    def add_event(self, name: str, attributes: Optional[Dict[str, Any]] = None) -> None:\n"
        "        self.events.append({\n"
        "            'name': name,\n"
        "            'timestamp': time.time(),\n"
        "            'attributes': attributes or {}\n"
        "        })\n"
        "\n"
        "    def finish(self, explicit_end_time: Optional[float] = None) -> None:\n"
        "        if self.end_time is None:\n"
        "            self.end_time = explicit_end_time if explicit_end_time is not None else time.time()\n"
        "            self.duration_ms = max(0.0, (self.end_time - self.start_time) * 1000.0)\n"
        "\n"
        "\n"
        "class GenAITracer:\n"
        "    \"\"\"\n"
        "    Orchestrates hierarchical GenAI span lifecycles, active contexts, and trace buffering.\n"
        "    \"\"\"\n"
        "    def __init__(self, service_name: str = 'agent-forge-platform'):\n"
        "        self.service_name = service_name\n"
        "        self.root_spans: List[GenAISpan] = []\n"
        "        self._span_stack: List[GenAISpan] = []\n"
        "        self._current_trace_id: Optional[str] = None\n"
        "\n"
        "    def start_span(\n"
        "        self,\n"
        "        name: str,\n"
        "        attributes: Optional[Dict[str, Any]] = None,\n"
        "        start_time: Optional[float] = None\n"
        "    ) -> GenAISpan:\n"
        "        parent = self._span_stack[-1] if self._span_stack else None\n"
        "        trace_id = parent.trace_id if parent else (self._current_trace_id or f\"trace_{uuid.uuid4().hex[:12]}\")\n"
        "        self._current_trace_id = trace_id\n"
        "\n"
        "        span = GenAISpan(\n"
        "            name=name,\n"
        "            trace_id=trace_id,\n"
        "            parent_span_id=parent.span_id if parent else None,\n"
        "            start_time=start_time if start_time is not None else time.time(),\n"
        "            attributes=attributes or {}\n"
        "        )\n"
        "        span.set_attribute('service.name', self.service_name)\n"
        "\n"
        "        if parent:\n"
        "            parent.children.append(span)\n"
        "        else:\n"
        "            self.root_spans.append(span)\n"
        "\n"
        "        self._span_stack.append(span)\n"
        "        return span\n"
        "\n"
        "    def end_span(self, span: GenAISpan, explicit_end_time: Optional[float] = None) -> None:\n"
        "        span.finish(explicit_end_time=explicit_end_time)\n"
        "        if self._span_stack and self._span_stack[-1] == span:\n"
        "            self._span_stack.pop()\n"
        "        elif span in self._span_stack:\n"
        "            self._span_stack.remove(span)\n"
        "\n"
        "    def get_all_spans_flat(self, root: GenAISpan) -> List[GenAISpan]:\n"
        "        flat: List[GenAISpan] = [root]\n"
        "        for child in root.children:\n"
        "            flat.extend(self.get_all_spans_flat(child))\n"
        "        return flat\n"
        "\n"
        "print('GenAITracer and GenAISpan initialized.')"
    )

    # -------------------------------------------------------------------------
    # Cell 4: Simulating a Multi-Turn Production Agent Execution
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 4. Simulating a Multi-Turn Autonomous Agent Trace\n\n"
        "Let us simulate an enterprise agent responding to a customer inquiry:\n"
        "> *\"Where is my package for order 9182, and can I get a 49.00 USD refund if it was delayed?\"*\n\n"
        "The agent executes a multi-step trajectory:\n"
        "1. **Root Span**: `agent_turn_execution` (Session orchestrator)\n"
        "2. **Child 1**: `intent_routing` (Fast LLM router, 120 input / 35 output tokens)\n"
        "3. **Child 2**: `hybrid_retrieval` (BM25 sparse + Dense vector search for refund policies)\n"
        "4. **Child 3**: `reasoning_turn_1` (LLM deciding to query order status: 650 in / 85 out tokens)\n"
        "5. **Child 4**: `mcp_tool_execution:check_order_status` (MCP JSON-RPC call to ERP database)\n"
        "6. **Child 5**: `reasoning_turn_2` (LLM evaluating policy against ERP status: 890 in / 110 out tokens)\n"
        "7. **Child 6**: `mcp_tool_execution:issue_refund` (Payment gateway mutation with idempotency key)\n"
        "8. **Child 7**: `final_synthesis` (Generating user-facing grounded response: 1,120 in / 160 out tokens)\n\n"
        "We record simulated wall-clock timestamps so that realistic duration gaps and concurrency are accurately captured."
    )

    nb.add_code(
        "# Instantiate tracer\n"
        "tracer = GenAITracer(service_name='agent-forge-customer-support')\n"
        "base_t = time.time()\n"
        "\n"
        "# 1. Root Span: agent_turn_execution\n"
        "root_span = tracer.start_span('agent_turn_execution', start_time=base_t)\n"
        "root_span.set_attribute('gen_ai.system', 'agent-forge')\n"
        "root_span.set_attribute('session.id', 'sess_usr_9981')\n"
        "root_span.set_attribute('tenant.id', 'enterprise_retail_corp')\n"
        "\n"
        "# 2. Step: Intent Routing (Fast Model)\n"
        "s1 = tracer.start_span('intent_routing', start_time=base_t + 0.02)\n"
        "s1.set_attribute('gen_ai.operation.name', 'chat')\n"
        "s1.set_attribute('gen_ai.request.model', 'claude-3-5-haiku')\n"
        "s1.set_attribute('gen_ai.usage.prompt_tokens', 120)\n"
        "s1.set_attribute('gen_ai.usage.completion_tokens', 35)\n"
        "tracer.end_span(s1, explicit_end_time=base_t + 0.28)\n"
        "\n"
        "# 3. Step: Hybrid Vector + BM25 Retrieval\n"
        "s2 = tracer.start_span('hybrid_retrieval', start_time=base_t + 0.31)\n"
        "s2.set_attribute('gen_ai.operation.name', 'retrieval')\n"
        "s2.set_attribute('retrieval.dense_k', 10)\n"
        "s2.set_attribute('retrieval.sparse_k', 10)\n"
        "s2.set_attribute('retrieval.rrf_alpha', 60)\n"
        "tracer.end_span(s2, explicit_end_time=base_t + 0.49)\n"
        "\n"
        "# 4. Step: Reasoning Turn 1 (LLM Call)\n"
        "s3 = tracer.start_span('reasoning_turn_1', start_time=base_t + 0.52)\n"
        "s3.set_attribute('gen_ai.operation.name', 'chat')\n"
        "s3.set_attribute('gen_ai.request.model', 'claude-3-7-sonnet')\n"
        "s3.set_attribute('gen_ai.usage.prompt_tokens', 650)\n"
        "s3.set_attribute('gen_ai.usage.completion_tokens', 85)\n"
        "s3.set_attribute('gen_ai.response.finish_reasons', ['tool_calls'])\n"
        "tracer.end_span(s3, explicit_end_time=base_t + 1.48)\n"
        "\n"
        "# 5. Step: MCP Tool: check_order_status\n"
        "s4 = tracer.start_span('mcp_tool:check_order_status', start_time=base_t + 1.51)\n"
        "s4.set_attribute('gen_ai.operation.name', 'tool_execution')\n"
        "s4.set_attribute('gen_ai.tool.name', 'check_order_status')\n"
        "s4.set_attribute('tool.input_args', {'order_id': '9182'})\n"
        "s4.set_attribute('tool.status_code', 200)\n"
        "tracer.end_span(s4, explicit_end_time=base_t + 1.76)\n"
        "\n"
        "# 6. Step: Reasoning Turn 2 (LLM evaluates order & policy)\n"
        "s5 = tracer.start_span('reasoning_turn_2', start_time=base_t + 1.79)\n"
        "s5.set_attribute('gen_ai.operation.name', 'chat')\n"
        "s5.set_attribute('gen_ai.request.model', 'claude-3-7-sonnet')\n"
        "s5.set_attribute('gen_ai.usage.prompt_tokens', 890)\n"
        "s5.set_attribute('gen_ai.usage.completion_tokens', 110)\n"
        "s5.set_attribute('gen_ai.response.finish_reasons', ['tool_calls'])\n"
        "tracer.end_span(s5, explicit_end_time=base_t + 2.85)\n"
        "\n"
        "# 7. Step: MCP Tool: issue_refund (Mutating Tool with Idempotency Key)\n"
        "s6 = tracer.start_span('mcp_tool:issue_refund', start_time=base_t + 2.88)\n"
        "s6.set_attribute('gen_ai.operation.name', 'tool_execution')\n"
        "s6.set_attribute('gen_ai.tool.name', 'issue_refund')\n"
        "s6.set_attribute('idempotency_key', 'idem_tx_9182_refund_49')\n"
        "s6.set_attribute('payment.amount_usd', 49.00)\n"
        "tracer.end_span(s6, explicit_end_time=base_t + 3.22)\n"
        "\n"
        "# 8. Step: Final Synthesis (LLM writes customer explanation)\n"
        "s7 = tracer.start_span('final_synthesis', start_time=base_t + 3.26)\n"
        "s7.set_attribute('gen_ai.operation.name', 'chat')\n"
        "s7.set_attribute('gen_ai.request.model', 'claude-3-7-sonnet')\n"
        "s7.set_attribute('gen_ai.usage.prompt_tokens', 1120)\n"
        "s7.set_attribute('gen_ai.usage.completion_tokens', 160)\n"
        "s7.set_attribute('gen_ai.response.finish_reasons', ['stop'])\n"
        "tracer.end_span(s7, explicit_end_time=base_t + 4.35)\n"
        "\n"
        "# End Root Span\n"
        "tracer.end_span(root_span, explicit_end_time=base_t + 4.40)\n"
        "\n"
        "all_spans = tracer.get_all_spans_flat(root_span)\n"
        "print(f\"Trace recording completed. Captured {len(all_spans)} spans under trace ID {root_span.trace_id}.\")"
    )

    # -------------------------------------------------------------------------
    # Cell 5: Trace Tree Inspection & ASCII Formatting
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 5. Trace Tree Inspection & ASCII Audit View\n\n"
        "Let us inspect the hierarchical tree formatted with its metadata, token accounts, and millisecond latencies."
    )

    nb.add_code(
        "def format_ascii_tree(span: GenAISpan, indent: int = 0) -> str:\n"
        "    prefix = '  ' * indent + ('+-- ' if indent > 0 else '[ROOT] ')\n"
        "    meta = []\n"
        "    if 'gen_ai.request.model' in span.attributes:\n"
        "        meta.append(f\"model={span.attributes['gen_ai.request.model']}\")\n"
        "    if 'gen_ai.tool.name' in span.attributes:\n"
        "        meta.append(f\"tool={span.attributes['gen_ai.tool.name']}\")\n"
        "    if 'gen_ai.usage.prompt_tokens' in span.attributes:\n"
        "        p = span.attributes['gen_ai.usage.prompt_tokens']\n"
        "        c = span.attributes.get('gen_ai.usage.completion_tokens', 0)\n"
        "        meta.append(f\"tokens={p}in/{c}out\")\n"
        "    if 'idempotency_key' in span.attributes:\n"
        "        meta.append(f\"key={span.attributes['idempotency_key']}\")\n"
        "\n"
        "    meta_str = f\" [{', '.join(meta)}]\" if meta else \"\"\n"
        "    lines = [f\"{prefix}{span.name:<30} ({span.duration_ms:6.1f} ms){meta_str}\"]\n"
        "    for child in span.children:\n"
        "        lines.append(format_ascii_tree(child, indent + 1))\n"
        "    return '\\n'.join(lines)\n"
        "\n"
        "print('=' * 85)\n"
        "print('OPENTELEMETRY GenAI DISTRIBUTED TRACE HIERARCHY')\n"
        "print('=' * 85)\n"
        "print(format_ascii_tree(root_span))\n"
        "print('=' * 85)"
    )

    # -------------------------------------------------------------------------
    # Cell 6: Interactive Matplotlib Trace Waterfall Visualization
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 6. Interactive Matplotlib Trace Waterfall Visualization\n\n"
        "We build a dual-panel Gantt waterfall visualization:\n"
        "1. **Top Panel (Trace Waterfall)**: Horizontal bars showing each span's exact start-to-finish "
        "offsets from `t0` (in milliseconds). Spans are color-coded by architectural archetype:\n"
        "   - **Root Workflow Orchestration**: Slate Gray (`#334155`)\n"
        "   - **Model Inference (LLM)**: Royal Blue (`#2563eb`)\n"
        "   - **Hybrid Vector / BM25 Retrieval**: Teal (`#0d9488`)\n"
        "   - **MCP Tool Execution**: Amber / Coral (`#ea580c`)\n"
        "2. **Bottom Panel (Cumulative Token Accumulation & Cost)**: Shows progressive token consumption "
        "across the multi-turn agent trajectory, illustrating the accelerating token budget decay."
    )

    nb.add_code(
        "# Extract span metrics relative to trace start\n"
        "trace_start = root_span.start_time\n"
        "\n"
        "span_records = []\n"
        "for s in all_spans:\n"
        "    op_type = 'orchestrator'\n"
        "    if 'gen_ai.request.model' in s.attributes:\n"
        "        op_type = 'model_call'\n"
        "    elif 'retrieval' in s.name:\n"
        "        op_type = 'retrieval'\n"
        "    elif 'gen_ai.tool.name' in s.attributes or 'mcp_tool' in s.name:\n"
        "        op_type = 'tool_call'\n"
        "\n"
        "    p_tok = s.attributes.get('gen_ai.usage.prompt_tokens', 0)\n"
        "    c_tok = s.attributes.get('gen_ai.usage.completion_tokens', 0)\n"
        "    total_tok = p_tok + c_tok\n"
        "\n"
        "    # Pricing model: $3.00/M prompt, $15.00/M completion for Sonnet; $0.80/$4.00 for Haiku\n"
        "    model = s.attributes.get('gen_ai.request.model', '')\n"
        "    if 'haiku' in model:\n"
        "        cost = (p_tok * 0.80 + c_tok * 4.00) / 1_000_000\n"
        "    elif 'sonnet' in model:\n"
        "        cost = (p_tok * 3.00 + c_tok * 15.00) / 1_000_000\n"
        "    else:\n"
        "        cost = 0.0\n"
        "\n"
        "    span_records.append({\n"
        "        'name': s.name,\n"
        "        'start_ms': (s.start_time - trace_start) * 1000.0,\n"
        "        'end_ms': (s.end_time - trace_start) * 1000.0,\n"
        "        'duration_ms': s.duration_ms,\n"
        "        'type': op_type,\n"
        "        'prompt_tokens': p_tok,\n"
        "        'completion_tokens': c_tok,\n"
        "        'total_tokens': total_tok,\n"
        "        'cost_usd': cost,\n"
        "        'model': model\n"
        "    })\n"
        "\n"
        "df_spans = pd.DataFrame(span_records)\n"
        "\n"
        "# Color mapping\n"
        "color_map = {\n"
        "    'orchestrator': '#334155',\n"
        "    'model_call': '#2563eb',\n"
        "    'retrieval': '#0d9488',\n"
        "    'tool_call': '#ea580c'\n"
        "}\n"
        "\n"
        "fig, (ax_waterfall, ax_tokens) = plt.subplots(\n"
        "    2, 1, figsize=(14, 10), sharex=True, gridspec_kw={'height_ratios': [2.5, 1.2]}\n"
        ")\n"
        "\n"
        "# Render Waterfall Bars (in reverse index so root is at top)\n"
        "y_indices = list(range(len(df_spans)))[::-1]\n"
        "y_labels = [df_spans.iloc[i]['name'] for i in range(len(df_spans))][::-1]\n"
        "\n"
        "for idx, row in df_spans.iterrows():\n"
        "    y_pos = len(df_spans) - 1 - idx\n"
        "    bar_color = color_map[row['type']]\n"
        "    bar_width = max(row['duration_ms'], 15.0)  # visual minimum width\n"
        "\n"
        "    ax_waterfall.barh(\n"
        "        y=y_pos,\n"
        "        width=bar_width,\n"
        "        left=row['start_ms'],\n"
        "        height=0.55,\n"
        "        color=bar_color,\n"
        "        alpha=0.9,\n"
        "        edgecolor='#1e293b',\n"
        "        linewidth=1.2\n"
        "    )\n"
        "\n"
        "    # Annotation text inside or alongside bar\n"
        "    annotation = f\"{row['duration_ms']:.0f}ms\"\n"
        "    if row['total_tokens'] > 0:\n"
        "        annotation += f\" ({row['prompt_tokens']}in/{row['completion_tokens']}out)\"\n"
        "\n"
        "    ax_waterfall.text(\n"
        "        row['start_ms'] + bar_width + 30,\n"
        "        y_pos,\n"
        "        annotation,\n"
        "        va='center',\n"
        "        ha='left',\n"
        "        fontsize=9,\n"
        "        fontweight='semibold',\n"
        "        color='#1e293b'\n"
        "    )\n"
        "\n"
        "ax_waterfall.set_yticks(range(len(df_spans)))\n"
        "ax_waterfall.set_yticklabels(y_labels, fontsize=10, fontweight='medium')\n"
        "ax_waterfall.set_title(\n"
        "    f\"OpenTelemetry GenAI Distributed Trace Waterfall (Trace ID: {root_span.trace_id[:16]}...)\",\n"
        "    fontsize=13, fontweight='bold', pad=12\n"
        ")\n"
        "ax_waterfall.grid(axis='x', linestyle='--', alpha=0.5)\n"
        "\n"
        "# Legend\n"
        "legend_handles = [\n"
        "    mpatches.Patch(color='#334155', label='Agent Orchestrator'),\n"
        "    mpatches.Patch(color='#2563eb', label='LLM Model Inference'),\n"
        "    mpatches.Patch(color='#0d9488', label='Vector Retrieval'),\n"
        "    mpatches.Patch(color='#ea580c', label='MCP Tool Execution')\n"
        "]\n"
        "ax_waterfall.legend(handles=legend_handles, loc='upper right', framealpha=0.9)\n"
        "\n"
        "# Render Bottom Panel: Cumulative Tokens over Time\n"
        "# Build time series steps\n"
        "times = [0.0]\n"
        "cum_tokens = [0]\n"
        "curr_tokens = 0\n"
        "\n"
        "for _, row in df_spans.sort_values('end_ms').iterrows():\n"
        "    if row['total_tokens'] > 0:\n"
        "        times.append(row['start_ms'])\n"
        "        cum_tokens.append(curr_tokens)\n"
        "        curr_tokens += row['total_tokens']\n"
        "        times.append(row['end_ms'])\n"
        "        cum_tokens.append(curr_tokens)\n"
        "\n"
        "times.append(root_span.duration_ms)\n"
        "cum_tokens.append(curr_tokens)\n"
        "\n"
        "ax_tokens.step(times, cum_tokens, where='post', color='#6366f1', linewidth=2.2, label='Cumulative Tokens')\n"
        "ax_tokens.fill_between(times, cum_tokens, step='post', alpha=0.15, color='#6366f1')\n"
        "ax_tokens.set_ylabel('Total Tokens', fontsize=10, fontweight='bold')\n"
        "ax_tokens.set_xlabel('Elapsed Execution Time (milliseconds)', fontsize=11, fontweight='bold')\n"
        "ax_tokens.grid(True, linestyle='--', alpha=0.5)\n"
        "\n"
        "# Secondary axis for cumulative dollar cost\n"
        "ax_cost = ax_tokens.twinx()\n"
        "total_cost = df_spans['cost_usd'].sum()\n"
        "cost_step = np.array(cum_tokens) / max(cum_tokens) * total_cost if max(cum_tokens) > 0 else np.zeros_like(cum_tokens)\n"
        "ax_cost.plot(times, cost_step, color='#059669', linestyle=':', linewidth=2.0, label='Incurred Cost ($)')\n"
        "ax_cost.set_ylabel('Cost (USD)', fontsize=10, fontweight='bold', color='#059669')\n"
        "ax_cost.tick_params(axis='y', labelcolor='#059669')\n"
        "\n"
        "plt.show()\n"
        "\n"
        "print(f\"Total Latency: {root_span.duration_ms:.1f} ms\")\n"
        "print(f\"Total Tokens Consumed: {df_spans['total_tokens'].sum():,}\")\n"
        "print(f\"Total Estimated Trace Cost: ${total_cost:.5f} USD\")"
    )

    # -------------------------------------------------------------------------
    # Cell 7: Latency & Cost Decomposition Analysis
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 7. Latency Decomposition & Cost Breakdown\n\n"
        "Let us analyze what fraction of execution time was consumed by LLM inference versus tool execution and retrieval. "
        "This breakdown is critical for performance tuning (e.g., determining whether to invest in speculative decoding "
        "vs database connection pooling)."
    )

    nb.add_code(
        "summary_by_type = df_spans[df_spans['type'] != 'orchestrator'].groupby('type').agg({\n"
        "    'duration_ms': 'sum',\n"
        "    'total_tokens': 'sum',\n"
        "    'cost_usd': 'sum'\n"
        "}).reset_index()\n"
        "\n"
        "total_sub_duration = summary_by_type['duration_ms'].sum()\n"
        "summary_by_type['latency_pct'] = (summary_by_type['duration_ms'] / total_sub_duration) * 100\n"
        "\n"
        "print(\"=\" * 75)\n"
        "print(\"PERFORMANCE & COST ATTRIBUTION BREAKDOWN\")\n"
        "print(\"=\" * 75)\n"
        "for _, row in summary_by_type.iterrows():\n"
        "    print(\n"
        "        f\"{row['type']:<15} | Latency: {row['duration_ms']:6.1f} ms ({row['latency_pct']:4.1f}%) | \"\n"
        "        f\"Tokens: {row['total_tokens']:5.0f} | Cost: ${row['cost_usd']:.5f}\"\n"
        "    )\n"
        "print(\"=\" * 75)\n"
        "\n"
        "# Architectural Takeaway\n"
        "model_latency_pct = summary_by_type[summary_by_type['type'] == 'model_call']['latency_pct'].values[0]\n"
        "print(f\"\\nKey Finding: LLM generation accounts for {model_latency_pct:.1f}% of total processing time.\")\n"
        "print(\"Optimizing vector index latency from 180ms to 50ms yields a marginal 3% end-to-end speedup,\")\n"
        "print(\"whereas streaming or model routing directly targets the dominant 80%+ bottleneck.\")"
    )

    # -------------------------------------------------------------------------
    # Cell 8: LLM-as-a-Judge Evaluation Harness
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 8. Offline Evaluation: Groundedness & Faithfulness LLM-as-a-Judge\n\n"
        "In production systems, traces tell us *how long* an agent took and *how many tokens* it consumed, "
        "but they cannot verify whether the agent output was **truthful** and **grounded** in evidence.\n\n"
        "### Groundedness vs Faithfulness Definitions:\n"
        "- **Groundedness**: Every statement in the output must be strictly supported by the retrieved context or tool response.\n"
        "- **Faithfulness**: The output must not invent facts, unauthorized amounts, or unverified claims (zero hallucinations).\n\n"
        "Below, we define a structured Pydantic evaluation schema and implement a deterministic evaluator mimicking "
        "the binary judge rubric used in `agent_forge.evals.groundedness`."
    )

    nb.add_code(
        "from pydantic import BaseModel, Field\n"
        "\n"
        "class EvaluationVerdict(BaseModel):\n"
        "    is_grounded: bool\n"
        "    score: float = Field(ge=0.0, le=1.0)\n"
        "    unsupported_claims: List[str]\n"
        "    reasoning: str\n"
        "\n"
        "class GroundednessJudge:\n"
        "    \"\"\"\n"
        "    Dual-rule factual consistency evaluator that verifies generated claims against evidence text.\n"
        "    Simulates an LLM-as-a-Judge with calibrated entity and quantity verification.\n"
        "    \"\"\"\n"
        "    def __init__(self, threshold: float = 0.80):\n"
        "        self.threshold = threshold\n"
        "\n"
        "    def evaluate(self, response: str, evidence_documents: List[str]) -> EvaluationVerdict:\n"
        "        combined_evidence = ' '.join(evidence_documents).lower()\n"
        "        resp_clean = response.lower()\n"
        "        unsupported = []\n"
        "\n"
        "        # 1. Entity and Order ID Check\n"
        "        import re\n"
        "        order_ids = re.findall(r'\\b\\d{4,6}\\b', resp_clean)\n"
        "        for oid in order_ids:\n"
        "            if oid not in combined_evidence:\n"
        "                unsupported.append(f\"Order ID '{oid}' cited in answer is missing from evidence.\")\n"
        "\n"
        "        # 2. Currency Amount Check\n"
        "        amounts = re.findall(r'\\$\\s*\\d+(?:\\.\\d{2})?|\\b\\d+(?:\\.\\d{2})?\\s*(?:usd|dollars)', resp_clean)\n"
        "        for amt in amounts:\n"
        "            digits_only = re.sub(r'[^0-9.]', '', amt)\n"
        "            if digits_only and digits_only not in combined_evidence:\n"
        "                unsupported.append(f\"Currency figure '{amt.strip()}' is ungrounded in evidence.\")\n"
        "\n"
        "        # 3. Unauthorized policy claims\n"
        "        hallucinated_phrases = ['immediate cash payout', 'unlimited free replacement', 'lifetime warranty guaranteed']\n"
        "        for phrase in hallucinated_phrases:\n"
        "            if phrase in resp_clean and phrase not in combined_evidence:\n"
        "                unsupported.append(f\"Unauthorized policy promise: '{phrase}'.\")\n"
        "\n"
        "        # Compute continuous score\n"
        "        if len(unsupported) == 0:\n"
        "            score = 1.0\n"
        "            reasoning = 'All factual claims, identifiers, and figures are fully supported by context.'\n"
        "        else:\n"
        "            penalty = min(0.95, len(unsupported) * 0.35)\n"
        "            score = max(0.05, 1.0 - penalty)\n"
        "            reasoning = f\"Detected {len(unsupported)} ungrounded claim(s): \" + '; '.join(unsupported)\n"
        "\n"
        "        is_grounded = (score >= self.threshold)\n"
        "        return EvaluationVerdict(\n"
        "            is_grounded=is_grounded,\n"
        "            score=round(score, 3),\n"
        "            unsupported_claims=unsupported,\n"
        "            reasoning=reasoning\n"
        "        )\n"
        "\n"
        "print('GroundednessJudge class defined with Pydantic v2 validation.')"
    )

    # -------------------------------------------------------------------------
    # Cell 9: Curation of Synthetic Evaluation Dataset
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 9. Curating a Synthetic Benchmark Evaluation Dataset\n\n"
        "To test our evaluation judge, we construct a calibrated benchmark dataset of 50 test cases:\n"
        "- **Ground-Truth Positive (Label = 1)**: Outputs that strictly stay within facts.\n"
        "- **Ground-Truth Negative (Label = 0)**: Outputs containing fabricated amounts, wrong order numbers, or unauthorized promises.\n"
        "- **Subtle Edge Cases**: Outputs with slight phrasing variations to test discrimination power."
    )

    nb.add_code(
        "# Benchmark Dataset Construction (50 Test Samples)\n"
        "np.random.seed(42)\n"
        "\n"
        "eval_samples = [\n"
        "    # Category 1: Grounded Responses (Label = 1)\n"
        "    {\n"
        "        'id': f'eval_{i:03d}',\n"
        "        'evidence': [\n"
        "            'Order 9182 was shipped on Monday and delayed due to weather.',\n"
        "            'Standard policy allows a $49.00 USD refund for delays exceeding 48 hours.'\n"
        "        ],\n"
        "        'response': f'Your package for order 9182 was delayed by weather. Per our policy, a refund of 49.00 USD has been credited (sample {i}).',\n"
        "        'ground_truth': 1\n"
        "    }\n"
        "    for i in range(1, 26)\n"
        "] + [\n"
        "    # Category 2: Hallucinated / Ungrounded Responses (Label = 0)\n"
        "    {\n"
        "        'id': f'eval_{i:03d}',\n"
        "        'evidence': [\n"
        "            'Order 9182 was shipped on Monday and delayed due to weather.',\n"
        "            'Standard policy allows a $49.00 USD refund for delays exceeding 48 hours.'\n"
        "        ],\n"
        "        'response': np.random.choice([\n"
        "            f'Order {9180 + i} is canceled and we issued a full cash payout of $250.00.',\n"
        "            f'Order 9182 qualifies for immediate cash payout of $49.00 USD plus unlimited free replacement.',\n"
        "            f'We issued a refund of $199.99 for order 9182 along with a lifetime warranty guaranteed.',\n"
        "            f'Your order 5521 was delivered yesterday and no refund is available.'\n"
        "        ]),\n"
        "        'ground_truth': 0\n"
        "    }\n"
        "    for i in range(26, 51)\n"
        "]\n"
        "\n"
        "df_eval = pd.DataFrame(eval_samples)\n"
        "print(f\"Evaluation benchmark ready: {len(df_eval)} samples ({df_eval['ground_truth'].value_counts().to_dict()})\")"
    )

    # -------------------------------------------------------------------------
    # Cell 10: Running the Judge & Computing Confusion Matrix
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 10. Executing the Evaluation Harness & Confusion Matrix\n\n"
        "We run the judge across all 50 samples, recording the continuous scores and predicted binary labels.\n"
        "We then compute:\n"
        "- **True Positives (TP)**: Grounded outputs correctly classified as Grounded.\n"
        "- **False Positives (FP)**: Hallucinations mistakenly accepted as Grounded (Severe Risk!).\n"
        "- **True Negatives (TN)**: Hallucinations correctly detected and rejected.\n"
        "- **False Negatives (FN)**: Grounded outputs falsely rejected (Over-cautious penalty)."
    )

    nb.add_code(
        "judge = GroundednessJudge(threshold=0.80)\n"
        "\n"
        "scores = []\n"
        "predictions = []\n"
        "reasons = []\n"
        "\n"
        "for _, row in df_eval.iterrows():\n"
        "    verdict = judge.evaluate(row['response'], row['evidence'])\n"
        "    scores.append(verdict.score)\n"
        "    predictions.append(1 if verdict.is_grounded else 0)\n"
        "    reasons.append(verdict.reasoning)\n"
        "\n"
        "df_eval['score'] = scores\n"
        "df_eval['pred'] = predictions\n"
        "df_eval['reasoning'] = reasons\n"
        "\n"
        "# Compute Confusion Matrix Elements\n"
        "tp = int(((df_eval['ground_truth'] == 1) & (df_eval['pred'] == 1)).sum())\n"
        "fp = int(((df_eval['ground_truth'] == 0) & (df_eval['pred'] == 1)).sum())\n"
        "fn = int(((df_eval['ground_truth'] == 1) & (df_eval['pred'] == 0)).sum())\n"
        "tn = int(((df_eval['ground_truth'] == 0) & (df_eval['pred'] == 0)).sum())\n"
        "\n"
        "accuracy = (tp + tn) / len(df_eval)\n"
        "precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0\n"
        "recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0\n"
        "f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0\n"
        "\n"
        "print(\"=\" * 65)\n"
        "print(\"EVALUATION HARNESS METRIC SCORECARD\")\n"
        "print(\"=\" * 65)\n"
        "print(f\"Accuracy:  {accuracy * 100:5.1f}%\")\n"
        "print(f\"Precision: {precision * 100:5.1f}% (Purity of accepted answers)\")\n"
        "print(f\"Recall:    {recall * 100:5.1f}% (Coverage of valid answers)\")\n"
        "print(f\"F1 Score:  {f1 * 100:5.1f}%\")\n"
        "print(f\"TP: {tp} | FP: {fp} | FN: {fn} | TN: {tn}\")\n"
        "print(\"=\" * 65)"
    )

    # -------------------------------------------------------------------------
    # Cell 11: Confusion Matrix Heatmap Plot
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 11. Confusion Matrix Heatmap\n\n"
        "Let us visualize the confusion matrix as a high-contrast heatmap."
    )

    nb.add_code(
        "cm = np.array([[tn, fp], [fn, tp]])\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(7, 6))\n"
        "sns.heatmap(\n"
        "    cm,\n"
        "    annot=True,\n"
        "    fmt='d',\n"
        "    cmap='Blues',\n"
        "    cbar=False,\n"
        "    xticklabels=['Predicted Hallucination (0)', 'Predicted Grounded (1)'],\n"
        "    yticklabels=['Actual Hallucination (0)', 'Actual Grounded (1)'],\n"
        "    annot_kws={'fontsize': 14, 'fontweight': 'bold'},\n"
        "    ax=ax\n"
        ")\n"
        "ax.set_title('LLM-as-a-Judge Confusion Matrix', fontsize=13, fontweight='bold', pad=14)\n"
        "ax.set_ylabel('Ground Truth', fontsize=11, fontweight='bold')\n"
        "ax.set_xlabel('Judge Classification', fontsize=11, fontweight='bold')\n"
        "plt.show()"
    )

    # -------------------------------------------------------------------------
    # Cell 12: Decision Threshold Tuning Curve
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 12. Decision Threshold Optimization Curve\n\n"
        "A critical engineering decision when deploying an LLM-as-a-judge is selecting the acceptance threshold "
        "`tau`. Setting `tau` too high causes the system to reject valid responses (high FN, lower recall). "
        "Setting `tau` too low allows hallucinations to slip past the gate into production (high FP, lower precision).\n\n"
        "Below, we sweep `tau` from 0.10 to 0.95 and plot the resulting Precision, Recall, and F1 curves to pinpoint "
        "the mathematically optimal threshold."
    )

    nb.add_code(
        "thresholds = np.linspace(0.10, 0.95, 30)\n"
        "precisions = []\n"
        "recalls = []\n"
        "f1_scores = []\n"
        "\n"
        "for tau in thresholds:\n"
        "    pred_tau = (df_eval['score'] >= tau).astype(int)\n"
        "    tp_t = int(((df_eval['ground_truth'] == 1) & (pred_tau == 1)).sum())\n"
        "    fp_t = int(((df_eval['ground_truth'] == 0) & (pred_tau == 1)).sum())\n"
        "    fn_t = int(((df_eval['ground_truth'] == 1) & (pred_tau == 0)).sum())\n"
        "\n"
        "    prec_t = tp_t / (tp_t + fp_t) if (tp_t + fp_t) > 0 else 1.0\n"
        "    rec_t = tp_t / (tp_t + fn_t) if (tp_t + fn_t) > 0 else 0.0\n"
        "    f1_t = (2 * prec_t * rec_t) / (prec_t + rec_t) if (prec_t + rec_t) > 0 else 0.0\n"
        "\n"
        "    precisions.append(prec_t)\n"
        "    recalls.append(rec_t)\n"
        "    f1_scores.append(f1_t)\n"
        "\n"
        "best_idx = np.argmax(f1_scores)\n"
        "best_threshold = thresholds[best_idx]\n"
        "best_f1 = f1_scores[best_idx]\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "ax.plot(thresholds, precisions, label='Precision (Zero Hallucination)', color='#059669', linewidth=2.2)\n"
        "ax.plot(thresholds, recalls, label='Recall (Valid Answer Coverage)', color='#2563eb', linewidth=2.2)\n"
        "ax.plot(thresholds, f1_scores, label='F1 Score (Harmonic Mean)', color='#d97706', linewidth=2.5, linestyle='--')\n"
        "\n"
        "ax.axvline(best_threshold, color='#dc2626', linestyle=':', linewidth=1.8, label=f'Optimal Tau = {best_threshold:.2f} (F1 = {best_f1:.2f})')\n"
        "ax.scatter([best_threshold], [best_f1], color='#dc2626', s=80, zorder=5)\n"
        "\n"
        "ax.set_title('Threshold Tuning: Balancing Hallucination Defense vs Answer Availability', fontsize=12, fontweight='bold', pad=12)\n"
        "ax.set_xlabel('Judge Acceptance Threshold (tau)', fontsize=11, fontweight='bold')\n"
        "ax.set_ylabel('Metric Value', fontsize=11, fontweight='bold')\n"
        "ax.set_ylim(-0.05, 1.05)\n"
        "ax.legend(loc='lower left', framealpha=0.9)\n"
        "ax.grid(True, linestyle='--', alpha=0.5)\n"
        "plt.show()\n"
        "\n"
        "print(f\"Calibrated Optimal Threshold: tau = {best_threshold:.2f}\")\n"
        "print(f\"Resulting F1 Score: {best_f1 * 100:.1f}%\")"
    )

    # -------------------------------------------------------------------------
    # Cell 13: The Closed-Loop Flywheel Architecture & Practice Exercises
    # -------------------------------------------------------------------------
    nb.add_markdown(
        "## 13. The Production Flywheel & Hands-On Engineering Challenges\n\n"
        "### Enterprise Closed-Loop Architecture\n"
        "In production AI platforms, tracing and evaluation do not exist in isolation. They form a **continuous flywheel**:\n"
        "1. **Online Spans**: High-latency or high-cost traces are flagged automatically.\n"
        "2. **Production Sampling**: The bottom 2% groundedness scores are routed to a human-in-the-loop triage queue.\n"
        "3. **Golden Dataset Expansion**: Curated edge cases are ingested into the offline evaluation suite.\n"
        "4. **CI/CD Quality Gates**: Every pull request must pass the offline eval suite before canary deployment.\n\n"
        "---\n\n"
        "### 🥋 Hands-On Katas for the Senior Engineer:\n"
        "1. **Task 1: Add Token Budget Degradation to Tracer**\n"
        "   - Modify `GenAITracer` so that if cumulative token consumption in a single trace exceeds 5,000 tokens, "
        "it emits an alert event and forces subsequent spans to route to a compact model (`claude-3-5-haiku`).\n"
        "2. **Task 2: Implement Tool Latency SLA Assertion**\n"
        "   - Write an evaluation rule asserting that no MCP tool execution span exceeds 350 milliseconds. "
        "Any trace violating this threshold should be tagged with `sla.violation=true`.\n"
        "3. **Task 3: Dual-Judge Cross-Validation**\n"
        "   - Add a second independent judge (e.g. testing syntactic answer relevance). "
        "Combine the two verdicts into an ensemble score using a weighted harmonic mean."
    )

    output_path = repo_root / "notebooks" / "06_eval_flywheel_and_trace_trees.ipynb"
    nb.save(output_path)
    return output_path


if __name__ == "__main__":
    p = build_notebook_06()
    print(f"Generated {p}")
